package hk.com.cts.ctcp.hotel.persistence;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * ExOrder generated by MyEclipse Persistence Tools
 */

public class ExOrder implements java.io.Serializable {

    // Fields
    // exorderid,序列号，主键唯一
    private Long exorderid;

    // 入住日期 不带时间的日期如 2008-08-08
    private Date checkindate;

    // 退房日期 不带时间的日期如 2008-08-08
    private Date checkoutdate;

    // 订单房间数量
    private Long roomquantity;

    // 面付/预付 值：pay : 面付 pre_pay : 预付
    private String paymethod;

    // 币种类型 RMB：人民币 、HKD：港币、USD：美金、MOP：奥门元、GBP：英镑、DEM：马克、JPY：日元
    private String currency;

    // 订单总金额，保留两位小数
    private Double totalamount;

    // 对换比率
    private Double exchangerate;

    // 人民币订单总金额，保留两位小数
    private Double localtotalamout;

    // 最早到店时间，保存格式如：14:00
    private String arrivaltime;

    // 最晚到店时间，保存格式如：19:00
    private String latestarrivaltime;

    // 是否需要无烟房
    private String nosmoking;

    // 给酒店的备注
    private String hotelnotes;

    // 客人特殊要求
    private String specialrequest;

    // 联系人姓名
    private String linkman;

    // 联系人称呼，D ：博士 ，P ： 教授 ，M ： 先生 ，R ： 太太 ，S ： 女士
    private String title;

    // 手机
    private String mobile;

    // 电话号码
    private String telephone;

    // 传真，不能含－等特殊符号，格式如：075583432343
    private String customerfax;

    // 电子邮箱
    private String email;

    // 去酒店坐什么交通工具（如飞机），4 : 轮船 、3 : 飞机 、2 : 火车 、1 : 汽车
    private String arrivaltraffic;

    // 车次（航班）
    private String flight;

    // 中英文，包括所有入住人的姓名，不同人名隔一个空格
    private String fellownames;

    // 成人数
    private Long adultnum;

    // 订单创建时间
    private Date createdate;

    // 修改时间
    private Date modifiedtime;

    // 酒店确认标志，1：确认，2：未确认，默认为2
    private Long hotelconfirm;

    // 酒店确认号，酒店提供的确认号
    private String hotelconfirmid;

    // noshow原因（内部使用）
    private String noshowreason;

    // 特别说明，日审使用（内部保留）
    private String specialnote;

    // 是否已担保
    private String isguarantee;

    // 保留字段，6PM(无担保)/TAGTD(公司担保)/CCGTD(信用卡担保，此种担保需要提供如下信用卡信息)
    private String guaranteetype;

    // 信用卡类型
    private String creditcardtype;

    // 信用卡名称
    private String creditcardname;

    // 信用卡卡号
    private String creditcardno;

    // 信用卡有效期
    private String creditcardexpires;

    // 支付状态（已完成支付）
    private String paysatus;

    // 订单状态(channel): 2：新单、21：已确认、14：已取消、4：已入住、13：noshow
    private Long orderstate;

    // 渠道类型，暂未分配
    private Long channeltype;

    // hotelId，芒果网内部酒店ID
    private Long hotelid;

    // hotelCode酒店编码
    private String hotelcode;

    // hotelCode(channel)各渠道对应的酒店编码
    private String hotelcodeforchannel;

    // 房型ID，芒果内部房型ID
    private Long roomtypeid;

    // 房型code
    private Long roomtypecode;

    // 房型ID(channel)各渠道对应的房型编码
    private String roomtypecodeforchannel;

    // 酒店中文名
    private String hotelname;

    // 子房型价格类型编码
    private Long pricetypecode;

    // 价格计划(channel)，各渠道对应的价格类型编码
    private String rateplancode;

    // 床型，1 : 大床 、2 : 双床 、3 : 单床
    private Long bedtype;

    // 房型中文名称
    private String roomtypename;

    // 芒果网内部orderId
    private Long orderid;

    // 内部orderCd
    private String ordercd;

    // 外部orderCd，（内部保留）
    private String ordercdhotel;

    // orderCd，渠道反回分配的订单编码，用于与渠道对帐日审处理
    private String ordercdforchannel;

    private List<ExOrderitem> exOrderitem = new ArrayList<ExOrderitem>();

    // Constructors

    /** default constructor */
    public ExOrder() {
    }

    /** minimal constructor */
    public ExOrder(Long exorderid, Date checkindate, Date checkoutdate, Long roomquantity,
        String paymethod, Double totalamount, Double exchangerate, Double localtotalamout,
        String linkman, Long adultnum, Long orderstate, Long channeltype, Long pricetypecode,
        Long orderid) {
        this.exorderid = exorderid;
        this.checkindate = checkindate;
        this.checkoutdate = checkoutdate;
        this.roomquantity = roomquantity;
        this.paymethod = paymethod;
        this.totalamount = totalamount;
        this.exchangerate = exchangerate;
        this.localtotalamout = localtotalamout;
        this.linkman = linkman;
        this.adultnum = adultnum;
        this.orderstate = orderstate;
        this.channeltype = channeltype;
        this.pricetypecode = pricetypecode;
        this.orderid = orderid;
    }

    /** full constructor */
    public ExOrder(Long exorderid, Date checkindate, Date checkoutdate, Long roomquantity,
        String paymethod, String currency, Double totalamount, Double exchangerate,
        Double localtotalamout, String arrivaltime, String latestarrivaltime, String nosmoking,
        String hotelnotes, String specialrequest, String linkman, String title, String mobile,
        String telephone, String customerfax, String email, String arrivaltraffic, String flight,
        String fellownames, Long adultnum, Date createdate, Date modifiedtime, Long hotelconfirm,
        String hotelconfirmid, String noshowreason, String specialnote, String isguarantee,
        String guaranteetype, String creditcardtype, String creditcardname, String creditcardno,
        String creditcardexpires, String paysatus, Long orderstate, Long channeltype, Long hotelid,
        String hotelcode, String hotelcodeforchannel, Long roomtypeid, Long roomtypecode,
        String roomtypecodeforchannel, String hotelname, Long pricetypecode, String rateplancode,
        Long bedtype, String roomtypename, Long orderid, String ordercd, String ordercdhotel,
        String ordercdforchannel) {
        this.exorderid = exorderid;
        this.checkindate = checkindate;
        this.checkoutdate = checkoutdate;
        this.roomquantity = roomquantity;
        this.paymethod = paymethod;
        this.currency = currency;
        this.totalamount = totalamount;
        this.exchangerate = exchangerate;
        this.localtotalamout = localtotalamout;
        this.arrivaltime = arrivaltime;
        this.latestarrivaltime = latestarrivaltime;
        this.nosmoking = nosmoking;
        this.hotelnotes = hotelnotes;
        this.specialrequest = specialrequest;
        this.linkman = linkman;
        this.title = title;
        this.mobile = mobile;
        this.telephone = telephone;
        this.customerfax = customerfax;
        this.email = email;
        this.arrivaltraffic = arrivaltraffic;
        this.flight = flight;
        this.fellownames = fellownames;
        this.adultnum = adultnum;
        this.createdate = createdate;
        this.modifiedtime = modifiedtime;
        this.hotelconfirm = hotelconfirm;
        this.hotelconfirmid = hotelconfirmid;
        this.noshowreason = noshowreason;
        this.specialnote = specialnote;
        this.isguarantee = isguarantee;
        this.guaranteetype = guaranteetype;
        this.creditcardtype = creditcardtype;
        this.creditcardname = creditcardname;
        this.creditcardno = creditcardno;
        this.creditcardexpires = creditcardexpires;
        this.paysatus = paysatus;
        this.orderstate = orderstate;
        this.channeltype = channeltype;
        this.hotelid = hotelid;
        this.hotelcode = hotelcode;
        this.hotelcodeforchannel = hotelcodeforchannel;
        this.roomtypeid = roomtypeid;
        this.roomtypecode = roomtypecode;
        this.roomtypecodeforchannel = roomtypecodeforchannel;
        this.hotelname = hotelname;
        this.pricetypecode = pricetypecode;
        this.rateplancode = rateplancode;
        this.bedtype = bedtype;
        this.roomtypename = roomtypename;
        this.orderid = orderid;
        this.ordercd = ordercd;
        this.ordercdhotel = ordercdhotel;
        this.ordercdforchannel = ordercdforchannel;
    }

    // Property accessors

    public Long getExorderid() {
        return this.exorderid;
    }

    public void setExorderid(Long exorderid) {
        this.exorderid = exorderid;
    }

    public Date getCheckindate() {
        return this.checkindate;
    }

    public void setCheckindate(Date checkindate) {
        this.checkindate = checkindate;
    }

    public Date getCheckoutdate() {
        return this.checkoutdate;
    }

    public void setCheckoutdate(Date checkoutdate) {
        this.checkoutdate = checkoutdate;
    }

    public Long getRoomquantity() {
        return this.roomquantity;
    }

    public void setRoomquantity(Long roomquantity) {
        this.roomquantity = roomquantity;
    }

    public String getPaymethod() {
        return this.paymethod;
    }

    public void setPaymethod(String paymethod) {
        this.paymethod = paymethod;
    }

    public String getCurrency() {
        return this.currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public Double getTotalamount() {
        return this.totalamount;
    }

    public void setTotalamount(Double totalamount) {
        this.totalamount = totalamount;
    }

    public Double getExchangerate() {
        return this.exchangerate;
    }

    public void setExchangerate(Double exchangerate) {
        this.exchangerate = exchangerate;
    }

    public Double getLocaltotalamout() {
        return this.localtotalamout;
    }

    public void setLocaltotalamout(Double localtotalamout) {
        this.localtotalamout = localtotalamout;
    }

    public String getArrivaltime() {
        return this.arrivaltime;
    }

    public void setArrivaltime(String arrivaltime) {
        this.arrivaltime = arrivaltime;
    }

    public String getLatestarrivaltime() {
        return this.latestarrivaltime;
    }

    public void setLatestarrivaltime(String latestarrivaltime) {
        this.latestarrivaltime = latestarrivaltime;
    }

    public String getNosmoking() {
        return this.nosmoking;
    }

    public void setNosmoking(String nosmoking) {
        this.nosmoking = nosmoking;
    }

    public String getHotelnotes() {
        return this.hotelnotes;
    }

    public void setHotelnotes(String hotelnotes) {
        this.hotelnotes = hotelnotes;
    }

    public String getSpecialrequest() {
        return this.specialrequest;
    }

    public void setSpecialrequest(String specialrequest) {
        this.specialrequest = specialrequest;
    }

    public String getLinkman() {
        return this.linkman;
    }

    public void setLinkman(String linkman) {
        this.linkman = linkman;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getTelephone() {
        return this.telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getCustomerfax() {
        return this.customerfax;
    }

    public void setCustomerfax(String customerfax) {
        this.customerfax = customerfax;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getArrivaltraffic() {
        return this.arrivaltraffic;
    }

    public void setArrivaltraffic(String arrivaltraffic) {
        this.arrivaltraffic = arrivaltraffic;
    }

    public String getFlight() {
        return this.flight;
    }

    public void setFlight(String flight) {
        this.flight = flight;
    }

    public String getFellownames() {
        return this.fellownames;
    }

    public void setFellownames(String fellownames) {
        this.fellownames = fellownames;
    }

    public Long getAdultnum() {
        return this.adultnum;
    }

    public void setAdultnum(Long adultnum) {
        this.adultnum = adultnum;
    }

    public Date getCreatedate() {
        return this.createdate;
    }

    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    public Date getModifiedtime() {
        return this.modifiedtime;
    }

    public void setModifiedtime(Date modifiedtime) {
        this.modifiedtime = modifiedtime;
    }

    public Long getHotelconfirm() {
        return this.hotelconfirm;
    }

    public void setHotelconfirm(Long hotelconfirm) {
        this.hotelconfirm = hotelconfirm;
    }

    public String getHotelconfirmid() {
        return this.hotelconfirmid;
    }

    public void setHotelconfirmid(String hotelconfirmid) {
        this.hotelconfirmid = hotelconfirmid;
    }

    public String getNoshowreason() {
        return this.noshowreason;
    }

    public void setNoshowreason(String noshowreason) {
        this.noshowreason = noshowreason;
    }

    public String getSpecialnote() {
        return this.specialnote;
    }

    public void setSpecialnote(String specialnote) {
        this.specialnote = specialnote;
    }

    public String getIsguarantee() {
        return this.isguarantee;
    }

    public void setIsguarantee(String isguarantee) {
        this.isguarantee = isguarantee;
    }

    public String getGuaranteetype() {
        return this.guaranteetype;
    }

    public void setGuaranteetype(String guaranteetype) {
        this.guaranteetype = guaranteetype;
    }

    public String getCreditcardtype() {
        return this.creditcardtype;
    }

    public void setCreditcardtype(String creditcardtype) {
        this.creditcardtype = creditcardtype;
    }

    public String getCreditcardname() {
        return this.creditcardname;
    }

    public void setCreditcardname(String creditcardname) {
        this.creditcardname = creditcardname;
    }

    public String getCreditcardno() {
        return this.creditcardno;
    }

    public void setCreditcardno(String creditcardno) {
        this.creditcardno = creditcardno;
    }

    public String getCreditcardexpires() {
        return this.creditcardexpires;
    }

    public void setCreditcardexpires(String creditcardexpires) {
        this.creditcardexpires = creditcardexpires;
    }

    public String getPaysatus() {
        return this.paysatus;
    }

    public void setPaysatus(String paysatus) {
        this.paysatus = paysatus;
    }

    public Long getOrderstate() {
        return this.orderstate;
    }

    public void setOrderstate(Long orderstate) {
        this.orderstate = orderstate;
    }

    public Long getChanneltype() {
        return this.channeltype;
    }

    public void setChanneltype(Long channeltype) {
        this.channeltype = channeltype;
    }

    public Long getHotelid() {
        return this.hotelid;
    }

    public void setHotelid(Long hotelid) {
        this.hotelid = hotelid;
    }

    public String getHotelcode() {
        return this.hotelcode;
    }

    public void setHotelcode(String hotelcode) {
        this.hotelcode = hotelcode;
    }

    public String getHotelcodeforchannel() {
        return this.hotelcodeforchannel;
    }

    public void setHotelcodeforchannel(String hotelcodeforchannel) {
        this.hotelcodeforchannel = hotelcodeforchannel;
    }

    public Long getRoomtypeid() {
        return this.roomtypeid;
    }

    public void setRoomtypeid(Long roomtypeid) {
        this.roomtypeid = roomtypeid;
    }

    public Long getRoomtypecode() {
        return this.roomtypecode;
    }

    public void setRoomtypecode(Long roomtypecode) {
        this.roomtypecode = roomtypecode;
    }

    public String getRoomtypecodeforchannel() {
        return this.roomtypecodeforchannel;
    }

    public void setRoomtypecodeforchannel(String roomtypecodeforchannel) {
        this.roomtypecodeforchannel = roomtypecodeforchannel;
    }

    public String getHotelname() {
        return this.hotelname;
    }

    public void setHotelname(String hotelname) {
        this.hotelname = hotelname;
    }

    public Long getPricetypecode() {
        return this.pricetypecode;
    }

    public void setPricetypecode(Long pricetypecode) {
        this.pricetypecode = pricetypecode;
    }

    public String getRateplancode() {
        return this.rateplancode;
    }

    public void setRateplancode(String rateplancode) {
        this.rateplancode = rateplancode;
    }

    public Long getBedtype() {
        return this.bedtype;
    }

    public void setBedtype(Long bedtype) {
        this.bedtype = bedtype;
    }

    public String getRoomtypename() {
        return this.roomtypename;
    }

    public void setRoomtypename(String roomtypename) {
        this.roomtypename = roomtypename;
    }

    public Long getOrderid() {
        return this.orderid;
    }

    public void setOrderid(Long orderid) {
        this.orderid = orderid;
    }

    public String getOrdercd() {
        return this.ordercd;
    }

    public void setOrdercd(String ordercd) {
        this.ordercd = ordercd;
    }

    public String getOrdercdhotel() {
        return this.ordercdhotel;
    }

    public void setOrdercdhotel(String ordercdhotel) {
        this.ordercdhotel = ordercdhotel;
    }

    public String getOrdercdforchannel() {
        return this.ordercdforchannel;
    }

    public void setOrdercdforchannel(String ordercdforchannel) {
        this.ordercdforchannel = ordercdforchannel;
    }

    public List<ExOrderitem> getExOrderitem() {
        return exOrderitem;
    }

    public void setExOrderitem(List<ExOrderitem> exOrderitem) {
        this.exOrderitem = exOrderitem;
    }

}