//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.13 at 05:51:26 ���� CST 
//


package zhx.dto;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RoomStays">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}RoomStay"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Services">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Service">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Price" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="TimeSpan">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="StartDate" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                                     &lt;attribute name="EndDate" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="VendorCode" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                           &lt;attribute name="RatePlanCode" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                           &lt;attribute name="ServiceCode" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                           &lt;attribute name="ServiceName" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                           &lt;attribute name="Quantity" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                           &lt;attribute name="ServiceDescription" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ResGuests">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ResGuest" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="GuestProfile" type="{}ProfileTypeHR"/>
 *                             &lt;element name="GuestIndex" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="RoomNumber" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="IsMobileContact" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ResGlobalInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="GuestCount" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="TimeSpan">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="StartDate" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                           &lt;attribute name="EndDate" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ArriveEarlyTime" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="ArriveLateTime" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="Payment" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ContactorInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Profile" type="{}ProfileTypeHR"/>
 *                   &lt;element name="IsMobileContact" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="IsEmailContact" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="IsTelephoneContact" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="IsFaxContact" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TotalAmount" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="GuaranteeInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CreditCardInfo">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="CardNum" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                           &lt;attribute name="CVV2" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                           &lt;attribute name="ExpireDate" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                           &lt;attribute name="OwnerName" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                           &lt;attribute name="CardType" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="GuaranteeType" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="ResOrderID" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="CreateDateTime" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ResStatus" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="CreateOrigResIndicator" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "roomStays",
    "services",
    "resGuests",
    "resGlobalInfo",
    "contactorInfo",
    "totalAmount",
    "guaranteeInfo"
})
@XmlRootElement(name = "HotelReservation")
public class HotelReservation {

    @XmlElement(name = "RoomStays", required = true)
    protected HotelReservation.RoomStays roomStays;
    @XmlElement(name = "Services", required = true)
    protected HotelReservation.Services services;
    @XmlElement(name = "ResGuests", required = true)
    protected HotelReservation.ResGuests resGuests;
    @XmlElement(name = "ResGlobalInfo", required = true)
    protected HotelReservation.ResGlobalInfo resGlobalInfo;
    @XmlElement(name = "ContactorInfo", required = true)
    protected HotelReservation.ContactorInfo contactorInfo;
    @XmlElement(name = "TotalAmount", required = true)
    protected Object totalAmount;
    @XmlElement(name = "GuaranteeInfo", required = true)
    protected HotelReservation.GuaranteeInfo guaranteeInfo;
    @XmlAttribute(name = "ResOrderID")
    @XmlSchemaType(name = "anySimpleType")
    protected String resOrderID;
    @XmlAttribute(name = "CreateDateTime")
    @XmlSchemaType(name = "anySimpleType")
    protected String createDateTime;
    @XmlAttribute(name = "ResStatus")
    @XmlSchemaType(name = "anySimpleType")
    protected String resStatus;
    @XmlAttribute(name = "CreateOrigResIndicator")
    @XmlSchemaType(name = "anySimpleType")
    protected String createOrigResIndicator;

    /**
     * Gets the value of the roomStays property.
     * 
     * @return
     *     possible object is
     *     {@link HotelReservation.RoomStays }
     *     
     */
    public HotelReservation.RoomStays getRoomStays() {
        return roomStays;
    }

    /**
     * Sets the value of the roomStays property.
     * 
     * @param value
     *     allowed object is
     *     {@link HotelReservation.RoomStays }
     *     
     */
    public void setRoomStays(HotelReservation.RoomStays value) {
        this.roomStays = value;
    }

    /**
     * Gets the value of the services property.
     * 
     * @return
     *     possible object is
     *     {@link HotelReservation.Services }
     *     
     */
    public HotelReservation.Services getServices() {
        return services;
    }

    /**
     * Sets the value of the services property.
     * 
     * @param value
     *     allowed object is
     *     {@link HotelReservation.Services }
     *     
     */
    public void setServices(HotelReservation.Services value) {
        this.services = value;
    }

    /**
     * Gets the value of the resGuests property.
     * 
     * @return
     *     possible object is
     *     {@link HotelReservation.ResGuests }
     *     
     */
    public HotelReservation.ResGuests getResGuests() {
        return resGuests;
    }

    /**
     * Sets the value of the resGuests property.
     * 
     * @param value
     *     allowed object is
     *     {@link HotelReservation.ResGuests }
     *     
     */
    public void setResGuests(HotelReservation.ResGuests value) {
        this.resGuests = value;
    }

    /**
     * Gets the value of the resGlobalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link HotelReservation.ResGlobalInfo }
     *     
     */
    public HotelReservation.ResGlobalInfo getResGlobalInfo() {
        return resGlobalInfo;
    }

    /**
     * Sets the value of the resGlobalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link HotelReservation.ResGlobalInfo }
     *     
     */
    public void setResGlobalInfo(HotelReservation.ResGlobalInfo value) {
        this.resGlobalInfo = value;
    }

    /**
     * Gets the value of the contactorInfo property.
     * 
     * @return
     *     possible object is
     *     {@link HotelReservation.ContactorInfo }
     *     
     */
    public HotelReservation.ContactorInfo getContactorInfo() {
        return contactorInfo;
    }

    /**
     * Sets the value of the contactorInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link HotelReservation.ContactorInfo }
     *     
     */
    public void setContactorInfo(HotelReservation.ContactorInfo value) {
        this.contactorInfo = value;
    }

    /**
     * Gets the value of the totalAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTotalAmount() {
        return totalAmount;
    }

    /**
     * Sets the value of the totalAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTotalAmount(Object value) {
        this.totalAmount = value;
    }

    /**
     * Gets the value of the guaranteeInfo property.
     * 
     * @return
     *     possible object is
     *     {@link HotelReservation.GuaranteeInfo }
     *     
     */
    public HotelReservation.GuaranteeInfo getGuaranteeInfo() {
        return guaranteeInfo;
    }

    /**
     * Sets the value of the guaranteeInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link HotelReservation.GuaranteeInfo }
     *     
     */
    public void setGuaranteeInfo(HotelReservation.GuaranteeInfo value) {
        this.guaranteeInfo = value;
    }

    /**
     * Gets the value of the resOrderID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResOrderID() {
        return resOrderID;
    }

    /**
     * Sets the value of the resOrderID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResOrderID(String value) {
        this.resOrderID = value;
    }

    /**
     * Gets the value of the createDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreateDateTime() {
        return createDateTime;
    }

    /**
     * Sets the value of the createDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreateDateTime(String value) {
        this.createDateTime = value;
    }

    /**
     * Gets the value of the resStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResStatus() {
        return resStatus;
    }

    /**
     * Sets the value of the resStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResStatus(String value) {
        this.resStatus = value;
    }

    /**
     * Gets the value of the createOrigResIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreateOrigResIndicator() {
        return createOrigResIndicator;
    }

    /**
     * Sets the value of the createOrigResIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreateOrigResIndicator(String value) {
        this.createOrigResIndicator = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Profile" type="{}ProfileTypeHR"/>
     *         &lt;element name="IsMobileContact" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="IsEmailContact" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="IsTelephoneContact" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="IsFaxContact" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "profile",
        "isMobileContact",
        "isEmailContact",
        "isTelephoneContact",
        "isFaxContact"
    })
    public static class ContactorInfo {

        @XmlElement(name = "Profile", required = true)
        protected ProfileTypeHR profile;
        @XmlElement(name = "IsMobileContact", required = true)
        protected Object isMobileContact;
        @XmlElement(name = "IsEmailContact", required = true)
        protected Object isEmailContact;
        @XmlElement(name = "IsTelephoneContact", required = true)
        protected Object isTelephoneContact;
        @XmlElement(name = "IsFaxContact", required = true)
        protected Object isFaxContact;

        /**
         * Gets the value of the profile property.
         * 
         * @return
         *     possible object is
         *     {@link ProfileTypeHR }
         *     
         */
        public ProfileTypeHR getProfile() {
            return profile;
        }

        /**
         * Sets the value of the profile property.
         * 
         * @param value
         *     allowed object is
         *     {@link ProfileTypeHR }
         *     
         */
        public void setProfile(ProfileTypeHR value) {
            this.profile = value;
        }

        /**
         * Gets the value of the isMobileContact property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getIsMobileContact() {
            return isMobileContact;
        }

        /**
         * Sets the value of the isMobileContact property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setIsMobileContact(Object value) {
            this.isMobileContact = value;
        }

        /**
         * Gets the value of the isEmailContact property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getIsEmailContact() {
            return isEmailContact;
        }

        /**
         * Sets the value of the isEmailContact property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setIsEmailContact(Object value) {
            this.isEmailContact = value;
        }

        /**
         * Gets the value of the isTelephoneContact property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getIsTelephoneContact() {
            return isTelephoneContact;
        }

        /**
         * Sets the value of the isTelephoneContact property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setIsTelephoneContact(Object value) {
            this.isTelephoneContact = value;
        }

        /**
         * Gets the value of the isFaxContact property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getIsFaxContact() {
            return isFaxContact;
        }

        /**
         * Sets the value of the isFaxContact property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setIsFaxContact(Object value) {
            this.isFaxContact = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CreditCardInfo">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="CardNum" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                 &lt;attribute name="CVV2" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                 &lt;attribute name="ExpireDate" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                 &lt;attribute name="OwnerName" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                 &lt;attribute name="CardType" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="GuaranteeType" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "creditCardInfo"
    })
    public static class GuaranteeInfo {

        @XmlElement(name = "CreditCardInfo", required = true)
        protected HotelReservation.GuaranteeInfo.CreditCardInfo creditCardInfo;
        @XmlAttribute(name = "GuaranteeType")
        @XmlSchemaType(name = "anySimpleType")
        protected String guaranteeType;

        /**
         * Gets the value of the creditCardInfo property.
         * 
         * @return
         *     possible object is
         *     {@link HotelReservation.GuaranteeInfo.CreditCardInfo }
         *     
         */
        public HotelReservation.GuaranteeInfo.CreditCardInfo getCreditCardInfo() {
            return creditCardInfo;
        }

        /**
         * Sets the value of the creditCardInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link HotelReservation.GuaranteeInfo.CreditCardInfo }
         *     
         */
        public void setCreditCardInfo(HotelReservation.GuaranteeInfo.CreditCardInfo value) {
            this.creditCardInfo = value;
        }

        /**
         * Gets the value of the guaranteeType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGuaranteeType() {
            return guaranteeType;
        }

        /**
         * Sets the value of the guaranteeType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGuaranteeType(String value) {
            this.guaranteeType = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="CardNum" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *       &lt;attribute name="CVV2" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *       &lt;attribute name="ExpireDate" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *       &lt;attribute name="OwnerName" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *       &lt;attribute name="CardType" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class CreditCardInfo {

            @XmlAttribute(name = "CardNum")
            @XmlSchemaType(name = "anySimpleType")
            protected String cardNum;
            @XmlAttribute(name = "CVV2")
            @XmlSchemaType(name = "anySimpleType")
            protected String cvv2;
            @XmlAttribute(name = "ExpireDate")
            @XmlSchemaType(name = "anySimpleType")
            protected String expireDate;
            @XmlAttribute(name = "OwnerName")
            @XmlSchemaType(name = "anySimpleType")
            protected String ownerName;
            @XmlAttribute(name = "CardType")
            @XmlSchemaType(name = "anySimpleType")
            protected String cardType;

            /**
             * Gets the value of the cardNum property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCardNum() {
                return cardNum;
            }

            /**
             * Sets the value of the cardNum property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCardNum(String value) {
                this.cardNum = value;
            }

            /**
             * Gets the value of the cvv2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCVV2() {
                return cvv2;
            }

            /**
             * Sets the value of the cvv2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCVV2(String value) {
                this.cvv2 = value;
            }

            /**
             * Gets the value of the expireDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExpireDate() {
                return expireDate;
            }

            /**
             * Sets the value of the expireDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExpireDate(String value) {
                this.expireDate = value;
            }

            /**
             * Gets the value of the ownerName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOwnerName() {
                return ownerName;
            }

            /**
             * Sets the value of the ownerName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOwnerName(String value) {
                this.ownerName = value;
            }

            /**
             * Gets the value of the cardType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCardType() {
                return cardType;
            }

            /**
             * Sets the value of the cardType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCardType(String value) {
                this.cardType = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="GuestCount" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="TimeSpan">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="StartDate" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                 &lt;attribute name="EndDate" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ArriveEarlyTime" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="ArriveLateTime" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="Payment" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "guestCount",
        "timeSpan",
        "arriveEarlyTime",
        "arriveLateTime",
        "payment"
    })
    public static class ResGlobalInfo {

        @XmlElement(name = "GuestCount", required = true)
        protected Object guestCount;
        @XmlElement(name = "TimeSpan", required = true)
        protected HotelReservation.ResGlobalInfo.TimeSpan timeSpan;
        @XmlElement(name = "ArriveEarlyTime", required = true)
        protected Object arriveEarlyTime;
        @XmlElement(name = "ArriveLateTime", required = true)
        protected Object arriveLateTime;
        @XmlElement(name = "Payment", required = true)
        protected Object payment;

        /**
         * Gets the value of the guestCount property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getGuestCount() {
            return guestCount;
        }

        /**
         * Sets the value of the guestCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setGuestCount(Object value) {
            this.guestCount = value;
        }

        /**
         * Gets the value of the timeSpan property.
         * 
         * @return
         *     possible object is
         *     {@link HotelReservation.ResGlobalInfo.TimeSpan }
         *     
         */
        public HotelReservation.ResGlobalInfo.TimeSpan getTimeSpan() {
            return timeSpan;
        }

        /**
         * Sets the value of the timeSpan property.
         * 
         * @param value
         *     allowed object is
         *     {@link HotelReservation.ResGlobalInfo.TimeSpan }
         *     
         */
        public void setTimeSpan(HotelReservation.ResGlobalInfo.TimeSpan value) {
            this.timeSpan = value;
        }

        /**
         * Gets the value of the arriveEarlyTime property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getArriveEarlyTime() {
            return arriveEarlyTime;
        }

        /**
         * Sets the value of the arriveEarlyTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setArriveEarlyTime(Object value) {
            this.arriveEarlyTime = value;
        }

        /**
         * Gets the value of the arriveLateTime property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getArriveLateTime() {
            return arriveLateTime;
        }

        /**
         * Sets the value of the arriveLateTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setArriveLateTime(Object value) {
            this.arriveLateTime = value;
        }

        /**
         * Gets the value of the payment property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getPayment() {
            return payment;
        }

        /**
         * Sets the value of the payment property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setPayment(Object value) {
            this.payment = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="StartDate" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *       &lt;attribute name="EndDate" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class TimeSpan {

            @XmlAttribute(name = "StartDate")
            @XmlSchemaType(name = "anySimpleType")
            protected String startDate;
            @XmlAttribute(name = "EndDate")
            @XmlSchemaType(name = "anySimpleType")
            protected String endDate;

            /**
             * Gets the value of the startDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStartDate() {
                return startDate;
            }

            /**
             * Sets the value of the startDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStartDate(String value) {
                this.startDate = value;
            }

            /**
             * Gets the value of the endDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEndDate() {
                return endDate;
            }

            /**
             * Sets the value of the endDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEndDate(String value) {
                this.endDate = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ResGuest" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="GuestProfile" type="{}ProfileTypeHR"/>
     *                   &lt;element name="GuestIndex" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="RoomNumber" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="IsMobileContact" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "resGuest"
    })
    public static class ResGuests {

        @XmlElement(name = "ResGuest", required = true)
        protected List<HotelReservation.ResGuests.ResGuest> resGuest;

        /**
         * Gets the value of the resGuest property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the resGuest property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getResGuest().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link HotelReservation.ResGuests.ResGuest }
         * 
         * 
         */
        public List<HotelReservation.ResGuests.ResGuest> getResGuest() {
            if (resGuest == null) {
                resGuest = new ArrayList<HotelReservation.ResGuests.ResGuest>();
            }
            return this.resGuest;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="GuestProfile" type="{}ProfileTypeHR"/>
         *         &lt;element name="GuestIndex" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="RoomNumber" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="IsMobileContact" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "guestProfile",
            "guestIndex",
            "type",
            "roomNumber",
            "isMobileContact"
        })
        public static class ResGuest {

            @XmlElement(name = "GuestProfile", required = true)
            protected ProfileTypeHR guestProfile;
            @XmlElement(name = "GuestIndex", required = true)
            protected Object guestIndex;
            @XmlElement(name = "Type", required = true)
            protected Object type;
            @XmlElement(name = "RoomNumber", required = true)
            protected Object roomNumber;
            @XmlElement(name = "IsMobileContact", required = true)
            protected Object isMobileContact;

            /**
             * Gets the value of the guestProfile property.
             * 
             * @return
             *     possible object is
             *     {@link ProfileTypeHR }
             *     
             */
            public ProfileTypeHR getGuestProfile() {
                return guestProfile;
            }

            /**
             * Sets the value of the guestProfile property.
             * 
             * @param value
             *     allowed object is
             *     {@link ProfileTypeHR }
             *     
             */
            public void setGuestProfile(ProfileTypeHR value) {
                this.guestProfile = value;
            }

            /**
             * Gets the value of the guestIndex property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getGuestIndex() {
                return guestIndex;
            }

            /**
             * Sets the value of the guestIndex property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setGuestIndex(Object value) {
                this.guestIndex = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setType(Object value) {
                this.type = value;
            }

            /**
             * Gets the value of the roomNumber property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getRoomNumber() {
                return roomNumber;
            }

            /**
             * Sets the value of the roomNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setRoomNumber(Object value) {
                this.roomNumber = value;
            }

            /**
             * Gets the value of the isMobileContact property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getIsMobileContact() {
                return isMobileContact;
            }

            /**
             * Sets the value of the isMobileContact property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setIsMobileContact(Object value) {
                this.isMobileContact = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}RoomStay"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "roomStay"
    })
    public static class RoomStays {

        @XmlElement(name = "RoomStay", required = true)
        protected RoomStay roomStay;

        /**
         * Gets the value of the roomStay property.
         * 
         * @return
         *     possible object is
         *     {@link RoomStay }
         *     
         */
        public RoomStay getRoomStay() {
            return roomStay;
        }

        /**
         * Sets the value of the roomStay property.
         * 
         * @param value
         *     allowed object is
         *     {@link RoomStay }
         *     
         */
        public void setRoomStay(RoomStay value) {
            this.roomStay = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Service">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Price" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="TimeSpan">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="StartDate" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                           &lt;attribute name="EndDate" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="VendorCode" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                 &lt;attribute name="RatePlanCode" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                 &lt;attribute name="ServiceCode" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                 &lt;attribute name="ServiceName" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                 &lt;attribute name="Quantity" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                 &lt;attribute name="ServiceDescription" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "service"
    })
    public static class Services {

        @XmlElement(name = "Service", required = true)
        protected HotelReservation.Services.Service service;

        /**
         * Gets the value of the service property.
         * 
         * @return
         *     possible object is
         *     {@link HotelReservation.Services.Service }
         *     
         */
        public HotelReservation.Services.Service getService() {
            return service;
        }

        /**
         * Sets the value of the service property.
         * 
         * @param value
         *     allowed object is
         *     {@link HotelReservation.Services.Service }
         *     
         */
        public void setService(HotelReservation.Services.Service value) {
            this.service = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Price" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="TimeSpan">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="StartDate" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *                 &lt;attribute name="EndDate" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="VendorCode" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *       &lt;attribute name="RatePlanCode" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *       &lt;attribute name="ServiceCode" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *       &lt;attribute name="ServiceName" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *       &lt;attribute name="Quantity" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *       &lt;attribute name="ServiceDescription" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "price",
            "timeSpan"
        })
        public static class Service {

            @XmlElement(name = "Price", required = true)
            protected Object price;
            @XmlElement(name = "TimeSpan", required = true)
            protected HotelReservation.Services.Service.TimeSpan timeSpan;
            @XmlAttribute(name = "VendorCode")
            @XmlSchemaType(name = "anySimpleType")
            protected String vendorCode;
            @XmlAttribute(name = "RatePlanCode")
            @XmlSchemaType(name = "anySimpleType")
            protected String ratePlanCode;
            @XmlAttribute(name = "ServiceCode")
            @XmlSchemaType(name = "anySimpleType")
            protected String serviceCode;
            @XmlAttribute(name = "ServiceName")
            @XmlSchemaType(name = "anySimpleType")
            protected String serviceName;
            @XmlAttribute(name = "Quantity")
            @XmlSchemaType(name = "anySimpleType")
            protected String quantity;
            @XmlAttribute(name = "ServiceDescription")
            @XmlSchemaType(name = "anySimpleType")
            protected String serviceDescription;

            /**
             * Gets the value of the price property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getPrice() {
                return price;
            }

            /**
             * Sets the value of the price property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setPrice(Object value) {
                this.price = value;
            }

            /**
             * Gets the value of the timeSpan property.
             * 
             * @return
             *     possible object is
             *     {@link HotelReservation.Services.Service.TimeSpan }
             *     
             */
            public HotelReservation.Services.Service.TimeSpan getTimeSpan() {
                return timeSpan;
            }

            /**
             * Sets the value of the timeSpan property.
             * 
             * @param value
             *     allowed object is
             *     {@link HotelReservation.Services.Service.TimeSpan }
             *     
             */
            public void setTimeSpan(HotelReservation.Services.Service.TimeSpan value) {
                this.timeSpan = value;
            }

            /**
             * Gets the value of the vendorCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVendorCode() {
                return vendorCode;
            }

            /**
             * Sets the value of the vendorCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVendorCode(String value) {
                this.vendorCode = value;
            }

            /**
             * Gets the value of the ratePlanCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRatePlanCode() {
                return ratePlanCode;
            }

            /**
             * Sets the value of the ratePlanCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRatePlanCode(String value) {
                this.ratePlanCode = value;
            }

            /**
             * Gets the value of the serviceCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getServiceCode() {
                return serviceCode;
            }

            /**
             * Sets the value of the serviceCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setServiceCode(String value) {
                this.serviceCode = value;
            }

            /**
             * Gets the value of the serviceName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getServiceName() {
                return serviceName;
            }

            /**
             * Sets the value of the serviceName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setServiceName(String value) {
                this.serviceName = value;
            }

            /**
             * Gets the value of the quantity property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getQuantity() {
                return quantity;
            }

            /**
             * Sets the value of the quantity property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setQuantity(String value) {
                this.quantity = value;
            }

            /**
             * Gets the value of the serviceDescription property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getServiceDescription() {
                return serviceDescription;
            }

            /**
             * Sets the value of the serviceDescription property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setServiceDescription(String value) {
                this.serviceDescription = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="StartDate" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
             *       &lt;attribute name="EndDate" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class TimeSpan {

                @XmlAttribute(name = "StartDate")
                @XmlSchemaType(name = "anySimpleType")
                protected String startDate;
                @XmlAttribute(name = "EndDate")
                @XmlSchemaType(name = "anySimpleType")
                protected String endDate;

                /**
                 * Gets the value of the startDate property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStartDate() {
                    return startDate;
                }

                /**
                 * Sets the value of the startDate property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStartDate(String value) {
                    this.startDate = value;
                }

                /**
                 * Gets the value of the endDate property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEndDate() {
                    return endDate;
                }

                /**
                 * Sets the value of the endDate property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEndDate(String value) {
                    this.endDate = value;
                }

            }

        }

    }

}
