//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.13 at 04:34:51 ���� CST 
//


package zhx.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * �Ƶ�����
 * 
 * <p>Java class for HotelDescriptiveContentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HotelDescriptiveContentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HotelBasicInfo" type="{}HotelInfoType"/>
 *         &lt;element name="ContactInfos" type="{}ContactInfosType"/>
 *         &lt;element name="Policies" type="{}PoliciesType"/>
 *         &lt;element name="FacilityInfos" type="{}FacilityInfosType"/>
 *         &lt;element name="Descriptions" type="{}DescriptionsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HotelDescriptiveContentType", propOrder = {
    "hotelBasicInfo",
    "contactInfos",
    "policies",
    "facilityInfos",
    "descriptions"
})
public class HotelDescriptiveContentType {

    @XmlElement(name = "HotelBasicInfo", required = true)
    protected HotelInfoType hotelBasicInfo;
    @XmlElement(name = "ContactInfos", required = true)
    protected ContactInfosType contactInfos;
    @XmlElement(name = "Policies", required = true)
    protected PoliciesType policies;
    @XmlElement(name = "FacilityInfos", required = true)
    protected FacilityInfosType facilityInfos;
    @XmlElement(name = "Descriptions", required = true)
    protected DescriptionsType descriptions;

    /**
     * Gets the value of the hotelBasicInfo property.
     * 
     * @return
     *     possible object is
     *     {@link HotelInfoType }
     *     
     */
    public HotelInfoType getHotelBasicInfo() {
        return hotelBasicInfo;
    }

    /**
     * Sets the value of the hotelBasicInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link HotelInfoType }
     *     
     */
    public void setHotelBasicInfo(HotelInfoType value) {
        this.hotelBasicInfo = value;
    }

    /**
     * Gets the value of the contactInfos property.
     * 
     * @return
     *     possible object is
     *     {@link ContactInfosType }
     *     
     */
    public ContactInfosType getContactInfos() {
        return contactInfos;
    }

    /**
     * Sets the value of the contactInfos property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactInfosType }
     *     
     */
    public void setContactInfos(ContactInfosType value) {
        this.contactInfos = value;
    }

    /**
     * Gets the value of the policies property.
     * 
     * @return
     *     possible object is
     *     {@link PoliciesType }
     *     
     */
    public PoliciesType getPolicies() {
        return policies;
    }

    /**
     * Sets the value of the policies property.
     * 
     * @param value
     *     allowed object is
     *     {@link PoliciesType }
     *     
     */
    public void setPolicies(PoliciesType value) {
        this.policies = value;
    }

    /**
     * Gets the value of the facilityInfos property.
     * 
     * @return
     *     possible object is
     *     {@link FacilityInfosType }
     *     
     */
    public FacilityInfosType getFacilityInfos() {
        return facilityInfos;
    }

    /**
     * Sets the value of the facilityInfos property.
     * 
     * @param value
     *     allowed object is
     *     {@link FacilityInfosType }
     *     
     */
    public void setFacilityInfos(FacilityInfosType value) {
        this.facilityInfos = value;
    }

    /**
     * Gets the value of the descriptions property.
     * 
     * @return
     *     possible object is
     *     {@link DescriptionsType }
     *     
     */
    public DescriptionsType getDescriptions() {
        return descriptions;
    }

    /**
     * Sets the value of the descriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescriptionsType }
     *     
     */
    public void setDescriptions(DescriptionsType value) {
        this.descriptions = value;
    }

}
