//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.13 at 05:51:26 ���� CST 
//


package zhx.dto;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the zhx package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactoryHARS {
	
	private final static QName _IdentityInfoTypeOfficeID_QNAME = new QName("", "OfficeID");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: zhx
     * 
     */
    public ObjectFactoryHARS() {
    }


    /**
     * Create an instance of {@link OTResponseHARS.HotelAvailRS.RoomStays }
     * 
     */
    public OTResponseHARS.HotelAvailRS.RoomStays createOTResponseHARSHotelAvailRSRoomStays() {
        return new OTResponseHARS.HotelAvailRS.RoomStays();
    }
    
    /**
     * Create an instance of {@link OTResponseHARS }
     * 
     */
    public OTResponseHARS createOTResponseHARS() {
        return new OTResponseHARS();
    }
    
    /**
     * Create an instance of {@link OTResponseHARS.HotelAvailRS }
     * 
     */
    public OTResponseHARS.HotelAvailRS createOTResponseHARSHotelAvailRS() {
        return new OTResponseHARS.HotelAvailRS();
    }
    
    /**
     * Create an instance of {@link OTResponseHARS.HotelAvailRS.RespPageInfo }
     * 
     */
    public OTResponseHARS.HotelAvailRS.RespPageInfo createOTResponseHARSHotelAvailRSRespPageInfo() {
        return new OTResponseHARS.HotelAvailRS.RespPageInfo();
    }
    
    /**
     * Create an instance of {@link OTResponseHARS.HotelAvailRS.Errors }
     * 
     */
    public OTResponseHARS.HotelAvailRS.Errors createOTResponseHARSHotelAvailRSErrors() {
        return new OTResponseHARS.HotelAvailRS.Errors();
    }
    
    /**
     * Create an instance of {@link OTResponseHARS.HotelAvailRS.Errors.Error }
     * 
     */
    public OTResponseHARS.HotelAvailRS.Errors.Error createOTResponseHARSHotelAvailRSErrorsError() {
        return new OTResponseHARS.HotelAvailRS.Errors.Error();
    }
    
    /**
     * Create an instance of {@link IdentityInfoType }
     * 
     */
    public IdentityInfoType createIdentityInfoType() {
        return new IdentityInfoType();
    }
    
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OfficeID", scope = IdentityInfoType.class)
    public JAXBElement<String> createIdentityInfoTypeOfficeID(String value) {
        return new JAXBElement<String>(_IdentityInfoTypeOfficeID_QNAME, String.class, IdentityInfoType.class, value);
    }
}
