//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.13 at 04:34:51 ���� CST 
//


package zhx.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TransactionName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="Header" type="{}HeaderType"/>
 *         &lt;element name="DestinationSystemCodes" type="{}DestinationSystemCodesType" minOccurs="0"/>
 *         &lt;element name="ResModifyAppInfoSearchRQ">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ResID">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="SubchannelTransCode" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="IdentityInfo" type="{}IdentityInfoType"/>
 *         &lt;element ref="{}Source"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transactionName",
    "header",
    "destinationSystemCodes",
    "resModifyAppInfoSearchRQ",
    "identityInfo",
    "source"
})
@XmlRootElement(name = "OTRequest")
public class OTRequestRMAISRQ {

    @XmlElement(name = "TransactionName", required = true)
    protected Object transactionName;
    @XmlElement(name = "Header", required = true)
    protected HeaderType header;
    @XmlElement(name = "DestinationSystemCodes")
    protected DestinationSystemCodesType destinationSystemCodes;
    @XmlElement(name = "ResModifyAppInfoSearchRQ", required = true)
    protected OTRequestRMAISRQ.ResModifyAppInfoSearchRQ resModifyAppInfoSearchRQ;
    @XmlElement(name = "IdentityInfo", required = true)
    protected IdentityInfoType identityInfo;
    @XmlElement(name = "Source", required = true)
    protected Source source;

    /**
     * Gets the value of the transactionName property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTransactionName() {
        return transactionName;
    }

    /**
     * Sets the value of the transactionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTransactionName(Object value) {
        this.transactionName = value;
    }

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link HeaderType }
     *     
     */
    public HeaderType getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeaderType }
     *     
     */
    public void setHeader(HeaderType value) {
        this.header = value;
    }

    /**
     * Gets the value of the destinationSystemCodes property.
     * 
     * @return
     *     possible object is
     *     {@link DestinationSystemCodesType }
     *     
     */
    public DestinationSystemCodesType getDestinationSystemCodes() {
        return destinationSystemCodes;
    }

    /**
     * Sets the value of the destinationSystemCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link DestinationSystemCodesType }
     *     
     */
    public void setDestinationSystemCodes(DestinationSystemCodesType value) {
        this.destinationSystemCodes = value;
    }

    /**
     * Gets the value of the resModifyAppInfoSearchRQ property.
     * 
     * @return
     *     possible object is
     *     {@link OTRequestRMAISRQ.ResModifyAppInfoSearchRQ }
     *     
     */
    public OTRequestRMAISRQ.ResModifyAppInfoSearchRQ getResModifyAppInfoSearchRQ() {
        return resModifyAppInfoSearchRQ;
    }

    /**
     * Sets the value of the resModifyAppInfoSearchRQ property.
     * 
     * @param value
     *     allowed object is
     *     {@link OTRequestRMAISRQ.ResModifyAppInfoSearchRQ }
     *     
     */
    public void setResModifyAppInfoSearchRQ(OTRequestRMAISRQ.ResModifyAppInfoSearchRQ value) {
        this.resModifyAppInfoSearchRQ = value;
    }

    /**
     * Gets the value of the identityInfo property.
     * 
     * @return
     *     possible object is
     *     {@link IdentityInfoType }
     *     
     */
    public IdentityInfoType getIdentityInfo() {
        return identityInfo;
    }

    /**
     * Sets the value of the identityInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentityInfoType }
     *     
     */
    public void setIdentityInfo(IdentityInfoType value) {
        this.identityInfo = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link Source }
     *     
     */
    public Source getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link Source }
     *     
     */
    public void setSource(Source value) {
        this.source = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ResID">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="SubchannelTransCode" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "resID",
        "subchannelTransCode"
    })
    public static class ResModifyAppInfoSearchRQ {

        @XmlElement(name = "ResID", required = true)
        protected OTRequestRMAISRQ.ResModifyAppInfoSearchRQ.ResID resID;
        @XmlElement(name = "SubchannelTransCode", required = true)
        protected Object subchannelTransCode;

        /**
         * Gets the value of the resID property.
         * 
         * @return
         *     possible object is
         *     {@link OTRequestRMAISRQ.ResModifyAppInfoSearchRQ.ResID }
         *     
         */
        public OTRequestRMAISRQ.ResModifyAppInfoSearchRQ.ResID getResID() {
            return resID;
        }

        /**
         * Sets the value of the resID property.
         * 
         * @param value
         *     allowed object is
         *     {@link OTRequestRMAISRQ.ResModifyAppInfoSearchRQ.ResID }
         *     
         */
        public void setResID(OTRequestRMAISRQ.ResModifyAppInfoSearchRQ.ResID value) {
            this.resID = value;
        }

        /**
         * Gets the value of the subchannelTransCode property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getSubchannelTransCode() {
            return subchannelTransCode;
        }

        /**
         * Sets the value of the subchannelTransCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setSubchannelTransCode(Object value) {
            this.subchannelTransCode = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class ResID {


        }

    }

}
