//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.13 at 04:34:51 ���� CST 
//


package zhx.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TrasactionName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="Header" type="{}HeaderType"/>
 *         &lt;element name="DestinationSystemCodes" type="{}DestinationSystemCodesType" minOccurs="0"/>
 *         &lt;element name="IdentityInfo" type="{}IdentityInfoType"/>
 *         &lt;element ref="{}Source"/>
 *         &lt;element name="HotelResMofityRS">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="Errors">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Error">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="ErrorCode" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                                     &lt;attribute name="ErrorDesc" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;sequence>
 *                     &lt;element name="Success" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                     &lt;element name="Warnings" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                     &lt;element name="ResModifyAppInfos">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element ref="{}ResModifyAppInfo"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trasactionName",
    "header",
    "destinationSystemCodes",
    "identityInfo",
    "source",
    "hotelResMofityRS"
})
@XmlRootElement(name = "OTResponse")
public class OTResponseTHHRMRS {

    @XmlElement(name = "TrasactionName", required = true)
    protected Object trasactionName;
    @XmlElement(name = "Header", required = true)
    protected HeaderType header;
    @XmlElement(name = "DestinationSystemCodes")
    protected DestinationSystemCodesType destinationSystemCodes;
    @XmlElement(name = "IdentityInfo", required = true)
    protected IdentityInfoType identityInfo;
    @XmlElement(name = "Source", required = true)
    protected Source source;
    @XmlElement(name = "HotelResMofityRS", required = true)
    protected OTResponseTHHRMRS.HotelResMofityRS hotelResMofityRS;

    /**
     * Gets the value of the trasactionName property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTrasactionName() {
        return trasactionName;
    }

    /**
     * Sets the value of the trasactionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTrasactionName(Object value) {
        this.trasactionName = value;
    }

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link HeaderType }
     *     
     */
    public HeaderType getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeaderType }
     *     
     */
    public void setHeader(HeaderType value) {
        this.header = value;
    }

    /**
     * Gets the value of the destinationSystemCodes property.
     * 
     * @return
     *     possible object is
     *     {@link DestinationSystemCodesType }
     *     
     */
    public DestinationSystemCodesType getDestinationSystemCodes() {
        return destinationSystemCodes;
    }

    /**
     * Sets the value of the destinationSystemCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link DestinationSystemCodesType }
     *     
     */
    public void setDestinationSystemCodes(DestinationSystemCodesType value) {
        this.destinationSystemCodes = value;
    }

    /**
     * Gets the value of the identityInfo property.
     * 
     * @return
     *     possible object is
     *     {@link IdentityInfoType }
     *     
     */
    public IdentityInfoType getIdentityInfo() {
        return identityInfo;
    }

    /**
     * Sets the value of the identityInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentityInfoType }
     *     
     */
    public void setIdentityInfo(IdentityInfoType value) {
        this.identityInfo = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link Source }
     *     
     */
    public Source getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link Source }
     *     
     */
    public void setSource(Source value) {
        this.source = value;
    }

    /**
     * Gets the value of the hotelResMofityRS property.
     * 
     * @return
     *     possible object is
     *     {@link OTResponseTHHRMRS.HotelResMofityRS }
     *     
     */
    public OTResponseTHHRMRS.HotelResMofityRS getHotelResMofityRS() {
        return hotelResMofityRS;
    }

    /**
     * Sets the value of the hotelResMofityRS property.
     * 
     * @param value
     *     allowed object is
     *     {@link OTResponseTHHRMRS.HotelResMofityRS }
     *     
     */
    public void setHotelResMofityRS(OTResponseTHHRMRS.HotelResMofityRS value) {
        this.hotelResMofityRS = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="Errors">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Error">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="ErrorCode" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                           &lt;attribute name="ErrorDesc" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;sequence>
     *           &lt;element name="Success" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *           &lt;element name="Warnings" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *           &lt;element name="ResModifyAppInfos">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;sequence>
     *                     &lt;element ref="{}ResModifyAppInfo"/>
     *                   &lt;/sequence>
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *         &lt;/sequence>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "errors",
        "success",
        "warnings",
        "resModifyAppInfos"
    })
    public static class HotelResMofityRS {

        @XmlElement(name = "Errors")
        protected OTResponseTHHRMRS.HotelResMofityRS.Errors errors;
        @XmlElement(name = "Success")
        protected Object success;
        @XmlElement(name = "Warnings")
        protected Object warnings;
        @XmlElement(name = "ResModifyAppInfos")
        protected OTResponseTHHRMRS.HotelResMofityRS.ResModifyAppInfos resModifyAppInfos;

        /**
         * Gets the value of the errors property.
         * 
         * @return
         *     possible object is
         *     {@link OTResponseTHHRMRS.HotelResMofityRS.Errors }
         *     
         */
        public OTResponseTHHRMRS.HotelResMofityRS.Errors getErrors() {
            return errors;
        }

        /**
         * Sets the value of the errors property.
         * 
         * @param value
         *     allowed object is
         *     {@link OTResponseTHHRMRS.HotelResMofityRS.Errors }
         *     
         */
        public void setErrors(OTResponseTHHRMRS.HotelResMofityRS.Errors value) {
            this.errors = value;
        }

        /**
         * Gets the value of the success property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getSuccess() {
            return success;
        }

        /**
         * Sets the value of the success property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setSuccess(Object value) {
            this.success = value;
        }

        /**
         * Gets the value of the warnings property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getWarnings() {
            return warnings;
        }

        /**
         * Sets the value of the warnings property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setWarnings(Object value) {
            this.warnings = value;
        }

        /**
         * Gets the value of the resModifyAppInfos property.
         * 
         * @return
         *     possible object is
         *     {@link OTResponseTHHRMRS.HotelResMofityRS.ResModifyAppInfos }
         *     
         */
        public OTResponseTHHRMRS.HotelResMofityRS.ResModifyAppInfos getResModifyAppInfos() {
            return resModifyAppInfos;
        }

        /**
         * Sets the value of the resModifyAppInfos property.
         * 
         * @param value
         *     allowed object is
         *     {@link OTResponseTHHRMRS.HotelResMofityRS.ResModifyAppInfos }
         *     
         */
        public void setResModifyAppInfos(OTResponseTHHRMRS.HotelResMofityRS.ResModifyAppInfos value) {
            this.resModifyAppInfos = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Error">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="ErrorCode" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *                 &lt;attribute name="ErrorDesc" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "error"
        })
        public static class Errors {

            @XmlElement(name = "Error", required = true)
            protected OTResponseTHHRMRS.HotelResMofityRS.Errors.Error error;

            /**
             * Gets the value of the error property.
             * 
             * @return
             *     possible object is
             *     {@link OTResponseTHHRMRS.HotelResMofityRS.Errors.Error }
             *     
             */
            public OTResponseTHHRMRS.HotelResMofityRS.Errors.Error getError() {
                return error;
            }

            /**
             * Sets the value of the error property.
             * 
             * @param value
             *     allowed object is
             *     {@link OTResponseTHHRMRS.HotelResMofityRS.Errors.Error }
             *     
             */
            public void setError(OTResponseTHHRMRS.HotelResMofityRS.Errors.Error value) {
                this.error = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="ErrorCode" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
             *       &lt;attribute name="ErrorDesc" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Error {

                @XmlAttribute(name = "ErrorCode")
                @XmlSchemaType(name = "anySimpleType")
                protected String errorCode;
                @XmlAttribute(name = "ErrorDesc")
                @XmlSchemaType(name = "anySimpleType")
                protected String errorDesc;

                /**
                 * Gets the value of the errorCode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getErrorCode() {
                    return errorCode;
                }

                /**
                 * Sets the value of the errorCode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setErrorCode(String value) {
                    this.errorCode = value;
                }

                /**
                 * Gets the value of the errorDesc property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getErrorDesc() {
                    return errorDesc;
                }

                /**
                 * Sets the value of the errorDesc property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setErrorDesc(String value) {
                    this.errorDesc = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{}ResModifyAppInfo"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "resModifyAppInfo"
        })
        public static class ResModifyAppInfos {

            @XmlElement(name = "ResModifyAppInfo", required = true)
            protected ResModifyAppInfo resModifyAppInfo;

            /**
             * Gets the value of the resModifyAppInfo property.
             * 
             * @return
             *     possible object is
             *     {@link ResModifyAppInfo }
             *     
             */
            public ResModifyAppInfo getResModifyAppInfo() {
                return resModifyAppInfo;
            }

            /**
             * Sets the value of the resModifyAppInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link ResModifyAppInfo }
             *     
             */
            public void setResModifyAppInfo(ResModifyAppInfo value) {
                this.resModifyAppInfo = value;
            }

        }

    }

}
