//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.13 at 04:34:51 ���� CST 
//


package zhx.dto;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TransactionName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="Header" type="{}HeaderType"/>
 *         &lt;element name="DestinationSystemCodes" type="{}DestinationSystemCodesType" minOccurs="0"/>
 *         &lt;element name="IdentityInfo" type="{}IdentityInfoType"/>
 *         &lt;element ref="{}Source"/>
 *         &lt;element name="HotelResSearchRS">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="Errors">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Error">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="ErrorCode" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                                     &lt;attribute name="ErrorDesc" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;sequence>
 *                     &lt;element name="Success" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                     &lt;element name="Warnings" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                     &lt;element name="HotelReservations">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element ref="{}HotelReservation" maxOccurs="unbounded"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="RespPageInfo">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="TotalPageNum" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                               &lt;element name="TotalNum" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                               &lt;element name="CurrentPage" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="HotelResBriefs">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="HotelResBrief">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;sequence>
 *                                         &lt;element name="ResID" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                         &lt;element name="CreateDate" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                         &lt;element name="CheckInDate" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                         &lt;element name="CheckOutDate" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                         &lt;element name="HotelName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                         &lt;element name="ResStatus" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                         &lt;element name="HotelCityCode" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                         &lt;element name="VendorCode" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                         &lt;element name="RoomTypeName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                         &lt;element name="GuestName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                         &lt;element name="RoomQuantity" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                         &lt;element name="RoomNight" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                         &lt;element name="Payment" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                         &lt;element name="TotalRateAmount" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;/sequence>
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transactionName",
    "header",
    "destinationSystemCodes",
    "identityInfo",
    "source",
    "hotelResSearchRS"
})
@XmlRootElement(name = "OTResponse")
public class OTResponseHResSRS {

    @XmlElement(name = "TransactionName", required = true)
    protected Object transactionName;
    @XmlElement(name = "Header", required = true)
    protected HeaderType header;
    @XmlElement(name = "DestinationSystemCodes")
    protected DestinationSystemCodesType destinationSystemCodes;
    @XmlElement(name = "IdentityInfo", required = true)
    protected IdentityInfoType identityInfo;
    @XmlElement(name = "Source", required = true)
    protected Source source;
    @XmlElement(name = "HotelResSearchRS", required = true)
    protected OTResponseHResSRS.HotelResSearchRS hotelResSearchRS;

    /**
     * Gets the value of the transactionName property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTransactionName() {
        return transactionName;
    }

    /**
     * Sets the value of the transactionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTransactionName(Object value) {
        this.transactionName = value;
    }

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link HeaderType }
     *     
     */
    public HeaderType getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeaderType }
     *     
     */
    public void setHeader(HeaderType value) {
        this.header = value;
    }

    /**
     * Gets the value of the destinationSystemCodes property.
     * 
     * @return
     *     possible object is
     *     {@link DestinationSystemCodesType }
     *     
     */
    public DestinationSystemCodesType getDestinationSystemCodes() {
        return destinationSystemCodes;
    }

    /**
     * Sets the value of the destinationSystemCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link DestinationSystemCodesType }
     *     
     */
    public void setDestinationSystemCodes(DestinationSystemCodesType value) {
        this.destinationSystemCodes = value;
    }

    /**
     * Gets the value of the identityInfo property.
     * 
     * @return
     *     possible object is
     *     {@link IdentityInfoType }
     *     
     */
    public IdentityInfoType getIdentityInfo() {
        return identityInfo;
    }

    /**
     * Sets the value of the identityInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentityInfoType }
     *     
     */
    public void setIdentityInfo(IdentityInfoType value) {
        this.identityInfo = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link Source }
     *     
     */
    public Source getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link Source }
     *     
     */
    public void setSource(Source value) {
        this.source = value;
    }

    /**
     * Gets the value of the hotelResSearchRS property.
     * 
     * @return
     *     possible object is
     *     {@link OTResponseHResSRS.HotelResSearchRS }
     *     
     */
    public OTResponseHResSRS.HotelResSearchRS getHotelResSearchRS() {
        return hotelResSearchRS;
    }

    /**
     * Sets the value of the hotelResSearchRS property.
     * 
     * @param value
     *     allowed object is
     *     {@link OTResponseHResSRS.HotelResSearchRS }
     *     
     */
    public void setHotelResSearchRS(OTResponseHResSRS.HotelResSearchRS value) {
        this.hotelResSearchRS = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="Errors">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Error">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="ErrorCode" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                           &lt;attribute name="ErrorDesc" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;sequence>
     *           &lt;element name="Success" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *           &lt;element name="Warnings" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *           &lt;element name="HotelReservations">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;sequence>
     *                     &lt;element ref="{}HotelReservation" maxOccurs="unbounded"/>
     *                   &lt;/sequence>
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *           &lt;element name="RespPageInfo">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;sequence>
     *                     &lt;element name="TotalPageNum" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                     &lt;element name="TotalNum" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                     &lt;element name="CurrentPage" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;/sequence>
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *           &lt;element name="HotelResBriefs">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;sequence>
     *                     &lt;element name="HotelResBrief">
     *                       &lt;complexType>
     *                         &lt;complexContent>
     *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                             &lt;sequence>
     *                               &lt;element name="ResID" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                               &lt;element name="CreateDate" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                               &lt;element name="CheckInDate" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                               &lt;element name="CheckOutDate" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                               &lt;element name="HotelName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                               &lt;element name="ResStatus" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                               &lt;element name="HotelCityCode" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                               &lt;element name="VendorCode" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                               &lt;element name="RoomTypeName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                               &lt;element name="GuestName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                               &lt;element name="RoomQuantity" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                               &lt;element name="RoomNight" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                               &lt;element name="Payment" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                               &lt;element name="TotalRateAmount" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;/sequence>
     *                           &lt;/restriction>
     *                         &lt;/complexContent>
     *                       &lt;/complexType>
     *                     &lt;/element>
     *                   &lt;/sequence>
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *         &lt;/sequence>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "errors",
        "success",
        "warnings",
        "hotelReservations",
        "respPageInfo",
        "hotelResBriefs"
    })
    public static class HotelResSearchRS {

        @XmlElement(name = "Errors")
        protected OTResponseHResSRS.HotelResSearchRS.Errors errors;
        @XmlElement(name = "Success")
        protected Object success;
        @XmlElement(name = "Warnings")
        protected Object warnings;
        @XmlElement(name = "HotelReservations")
        protected OTResponseHResSRS.HotelResSearchRS.HotelReservations hotelReservations;
        @XmlElement(name = "RespPageInfo")
        protected OTResponseHResSRS.HotelResSearchRS.RespPageInfo respPageInfo;
        @XmlElement(name = "HotelResBriefs")
        protected OTResponseHResSRS.HotelResSearchRS.HotelResBriefs hotelResBriefs;

        /**
         * Gets the value of the errors property.
         * 
         * @return
         *     possible object is
         *     {@link OTResponseHResSRS.HotelResSearchRS.Errors }
         *     
         */
        public OTResponseHResSRS.HotelResSearchRS.Errors getErrors() {
            return errors;
        }

        /**
         * Sets the value of the errors property.
         * 
         * @param value
         *     allowed object is
         *     {@link OTResponseHResSRS.HotelResSearchRS.Errors }
         *     
         */
        public void setErrors(OTResponseHResSRS.HotelResSearchRS.Errors value) {
            this.errors = value;
        }

        /**
         * Gets the value of the success property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getSuccess() {
            return success;
        }

        /**
         * Sets the value of the success property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setSuccess(Object value) {
            this.success = value;
        }

        /**
         * Gets the value of the warnings property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getWarnings() {
            return warnings;
        }

        /**
         * Sets the value of the warnings property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setWarnings(Object value) {
            this.warnings = value;
        }

        /**
         * Gets the value of the hotelReservations property.
         * 
         * @return
         *     possible object is
         *     {@link OTResponseHResSRS.HotelResSearchRS.HotelReservations }
         *     
         */
        public OTResponseHResSRS.HotelResSearchRS.HotelReservations getHotelReservations() {
            return hotelReservations;
        }

        /**
         * Sets the value of the hotelReservations property.
         * 
         * @param value
         *     allowed object is
         *     {@link OTResponseHResSRS.HotelResSearchRS.HotelReservations }
         *     
         */
        public void setHotelReservations(OTResponseHResSRS.HotelResSearchRS.HotelReservations value) {
            this.hotelReservations = value;
        }

        /**
         * Gets the value of the respPageInfo property.
         * 
         * @return
         *     possible object is
         *     {@link OTResponseHResSRS.HotelResSearchRS.RespPageInfo }
         *     
         */
        public OTResponseHResSRS.HotelResSearchRS.RespPageInfo getRespPageInfo() {
            return respPageInfo;
        }

        /**
         * Sets the value of the respPageInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link OTResponseHResSRS.HotelResSearchRS.RespPageInfo }
         *     
         */
        public void setRespPageInfo(OTResponseHResSRS.HotelResSearchRS.RespPageInfo value) {
            this.respPageInfo = value;
        }

        /**
         * Gets the value of the hotelResBriefs property.
         * 
         * @return
         *     possible object is
         *     {@link OTResponseHResSRS.HotelResSearchRS.HotelResBriefs }
         *     
         */
        public OTResponseHResSRS.HotelResSearchRS.HotelResBriefs getHotelResBriefs() {
            return hotelResBriefs;
        }

        /**
         * Sets the value of the hotelResBriefs property.
         * 
         * @param value
         *     allowed object is
         *     {@link OTResponseHResSRS.HotelResSearchRS.HotelResBriefs }
         *     
         */
        public void setHotelResBriefs(OTResponseHResSRS.HotelResSearchRS.HotelResBriefs value) {
            this.hotelResBriefs = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Error">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="ErrorCode" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *                 &lt;attribute name="ErrorDesc" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "error"
        })
        public static class Errors {

            @XmlElement(name = "Error", required = true)
            protected OTResponseHResSRS.HotelResSearchRS.Errors.Error error;

            /**
             * Gets the value of the error property.
             * 
             * @return
             *     possible object is
             *     {@link OTResponseHResSRS.HotelResSearchRS.Errors.Error }
             *     
             */
            public OTResponseHResSRS.HotelResSearchRS.Errors.Error getError() {
                return error;
            }

            /**
             * Sets the value of the error property.
             * 
             * @param value
             *     allowed object is
             *     {@link OTResponseHResSRS.HotelResSearchRS.Errors.Error }
             *     
             */
            public void setError(OTResponseHResSRS.HotelResSearchRS.Errors.Error value) {
                this.error = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="ErrorCode" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
             *       &lt;attribute name="ErrorDesc" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Error {

                @XmlAttribute(name = "ErrorCode")
                @XmlSchemaType(name = "anySimpleType")
                protected String errorCode;
                @XmlAttribute(name = "ErrorDesc")
                @XmlSchemaType(name = "anySimpleType")
                protected String errorDesc;

                /**
                 * Gets the value of the errorCode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getErrorCode() {
                    return errorCode;
                }

                /**
                 * Sets the value of the errorCode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setErrorCode(String value) {
                    this.errorCode = value;
                }

                /**
                 * Gets the value of the errorDesc property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getErrorDesc() {
                    return errorDesc;
                }

                /**
                 * Sets the value of the errorDesc property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setErrorDesc(String value) {
                    this.errorDesc = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="HotelResBrief">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="ResID" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="CreateDate" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="CheckInDate" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="CheckOutDate" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="HotelName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="ResStatus" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="HotelCityCode" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="VendorCode" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="RoomTypeName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="GuestName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="RoomQuantity" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="RoomNight" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="Payment" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="TotalRateAmount" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "hotelResBrief"
        })
        public static class HotelResBriefs {

            @XmlElement(name = "HotelResBrief", required = true)
            protected OTResponseHResSRS.HotelResSearchRS.HotelResBriefs.HotelResBrief hotelResBrief;

            /**
             * Gets the value of the hotelResBrief property.
             * 
             * @return
             *     possible object is
             *     {@link OTResponseHResSRS.HotelResSearchRS.HotelResBriefs.HotelResBrief }
             *     
             */
            public OTResponseHResSRS.HotelResSearchRS.HotelResBriefs.HotelResBrief getHotelResBrief() {
                return hotelResBrief;
            }

            /**
             * Sets the value of the hotelResBrief property.
             * 
             * @param value
             *     allowed object is
             *     {@link OTResponseHResSRS.HotelResSearchRS.HotelResBriefs.HotelResBrief }
             *     
             */
            public void setHotelResBrief(OTResponseHResSRS.HotelResSearchRS.HotelResBriefs.HotelResBrief value) {
                this.hotelResBrief = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="ResID" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="CreateDate" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="CheckInDate" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="CheckOutDate" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="HotelName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="ResStatus" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="HotelCityCode" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="VendorCode" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="RoomTypeName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="GuestName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="RoomQuantity" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="RoomNight" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="Payment" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="TotalRateAmount" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "resID",
                "createDate",
                "checkInDate",
                "checkOutDate",
                "hotelName",
                "resStatus",
                "hotelCityCode",
                "vendorCode",
                "roomTypeName",
                "guestName",
                "roomQuantity",
                "roomNight",
                "payment",
                "totalRateAmount"
            })
            public static class HotelResBrief {

                @XmlElement(name = "ResID", required = true)
                protected Object resID;
                @XmlElement(name = "CreateDate", required = true)
                protected Object createDate;
                @XmlElement(name = "CheckInDate", required = true)
                protected Object checkInDate;
                @XmlElement(name = "CheckOutDate", required = true)
                protected Object checkOutDate;
                @XmlElement(name = "HotelName", required = true)
                protected Object hotelName;
                @XmlElement(name = "ResStatus", required = true)
                protected Object resStatus;
                @XmlElement(name = "HotelCityCode", required = true)
                protected Object hotelCityCode;
                @XmlElement(name = "VendorCode", required = true)
                protected Object vendorCode;
                @XmlElement(name = "RoomTypeName", required = true)
                protected Object roomTypeName;
                @XmlElement(name = "GuestName", required = true)
                protected Object guestName;
                @XmlElement(name = "RoomQuantity", required = true)
                protected Object roomQuantity;
                @XmlElement(name = "RoomNight", required = true)
                protected Object roomNight;
                @XmlElement(name = "Payment", required = true)
                protected Object payment;
                @XmlElement(name = "TotalRateAmount", required = true)
                protected Object totalRateAmount;

                /**
                 * Gets the value of the resID property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getResID() {
                    return resID;
                }

                /**
                 * Sets the value of the resID property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setResID(Object value) {
                    this.resID = value;
                }

                /**
                 * Gets the value of the createDate property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getCreateDate() {
                    return createDate;
                }

                /**
                 * Sets the value of the createDate property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setCreateDate(Object value) {
                    this.createDate = value;
                }

                /**
                 * Gets the value of the checkInDate property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getCheckInDate() {
                    return checkInDate;
                }

                /**
                 * Sets the value of the checkInDate property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setCheckInDate(Object value) {
                    this.checkInDate = value;
                }

                /**
                 * Gets the value of the checkOutDate property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getCheckOutDate() {
                    return checkOutDate;
                }

                /**
                 * Sets the value of the checkOutDate property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setCheckOutDate(Object value) {
                    this.checkOutDate = value;
                }

                /**
                 * Gets the value of the hotelName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getHotelName() {
                    return hotelName;
                }

                /**
                 * Sets the value of the hotelName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setHotelName(Object value) {
                    this.hotelName = value;
                }

                /**
                 * Gets the value of the resStatus property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getResStatus() {
                    return resStatus;
                }

                /**
                 * Sets the value of the resStatus property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setResStatus(Object value) {
                    this.resStatus = value;
                }

                /**
                 * Gets the value of the hotelCityCode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getHotelCityCode() {
                    return hotelCityCode;
                }

                /**
                 * Sets the value of the hotelCityCode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setHotelCityCode(Object value) {
                    this.hotelCityCode = value;
                }

                /**
                 * Gets the value of the vendorCode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getVendorCode() {
                    return vendorCode;
                }

                /**
                 * Sets the value of the vendorCode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setVendorCode(Object value) {
                    this.vendorCode = value;
                }

                /**
                 * Gets the value of the roomTypeName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getRoomTypeName() {
                    return roomTypeName;
                }

                /**
                 * Sets the value of the roomTypeName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setRoomTypeName(Object value) {
                    this.roomTypeName = value;
                }

                /**
                 * Gets the value of the guestName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getGuestName() {
                    return guestName;
                }

                /**
                 * Sets the value of the guestName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setGuestName(Object value) {
                    this.guestName = value;
                }

                /**
                 * Gets the value of the roomQuantity property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getRoomQuantity() {
                    return roomQuantity;
                }

                /**
                 * Sets the value of the roomQuantity property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setRoomQuantity(Object value) {
                    this.roomQuantity = value;
                }

                /**
                 * Gets the value of the roomNight property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getRoomNight() {
                    return roomNight;
                }

                /**
                 * Sets the value of the roomNight property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setRoomNight(Object value) {
                    this.roomNight = value;
                }

                /**
                 * Gets the value of the payment property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getPayment() {
                    return payment;
                }

                /**
                 * Sets the value of the payment property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setPayment(Object value) {
                    this.payment = value;
                }

                /**
                 * Gets the value of the totalRateAmount property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getTotalRateAmount() {
                    return totalRateAmount;
                }

                /**
                 * Sets the value of the totalRateAmount property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setTotalRateAmount(Object value) {
                    this.totalRateAmount = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{}HotelReservation" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "hotelReservation"
        })
        public static class HotelReservations {

            @XmlElement(name = "HotelReservation", required = true)
            protected List<HotelReservation> hotelReservation;

            /**
             * Gets the value of the hotelReservation property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the hotelReservation property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getHotelReservation().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link HotelReservation }
             * 
             * 
             */
            public List<HotelReservation> getHotelReservation() {
                if (hotelReservation == null) {
                    hotelReservation = new ArrayList<HotelReservation>();
                }
                return this.hotelReservation;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="TotalPageNum" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="TotalNum" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="CurrentPage" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "totalPageNum",
            "totalNum",
            "currentPage"
        })
        public static class RespPageInfo {

            @XmlElement(name = "TotalPageNum", required = true)
            protected Object totalPageNum;
            @XmlElement(name = "TotalNum", required = true)
            protected Object totalNum;
            @XmlElement(name = "CurrentPage", required = true)
            protected Object currentPage;

            /**
             * Gets the value of the totalPageNum property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getTotalPageNum() {
                return totalPageNum;
            }

            /**
             * Sets the value of the totalPageNum property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setTotalPageNum(Object value) {
                this.totalPageNum = value;
            }

            /**
             * Gets the value of the totalNum property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getTotalNum() {
                return totalNum;
            }

            /**
             * Sets the value of the totalNum property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setTotalNum(Object value) {
                this.totalNum = value;
            }

            /**
             * Gets the value of the currentPage property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getCurrentPage() {
                return currentPage;
            }

            /**
             * Sets the value of the currentPage property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setCurrentPage(Object value) {
                this.currentPage = value;
            }

        }

    }

}
