package com.mangocity.hotel.base.persistence;

import com.mangocity.util.Entity;

/**
 * HtlAddscope generated by MyEclipse - Hibernate Tools
 */

public class HtlAddscope extends CEntity implements Entity {

    // Fields

    // 销售加幅id
    private Long ID;

    // 房型id
    private long roomTypeId;

    /**
     * 价格类型
     */
    private long priceTypeId;

    /**
     * 加幅类型
     */
    private String addType;

    /**
     * 面付加幅
     */
    private double addScope;

    /**
     * 预付加幅
     */
    private double preAddScope;

    private HtlAddscopeHdr addScopeHdr;

    // Constructors

    public HtlAddscopeHdr getAddScopeHdr() {
        return addScopeHdr;
    }

    public void setAddScopeHdr(HtlAddscopeHdr addScopeHdr) {
        this.addScopeHdr = addScopeHdr;
    }

    /** default constructor */
    public HtlAddscope() {
    }

    public double getAddScope() {
        return addScope;
    }

    public void setAddScope(double addScope) {
        this.addScope = addScope;
    }

    public double getPreAddScope() {
        return preAddScope;
    }

    public void setPreAddScope(double preAddScope) {
        this.preAddScope = preAddScope;
    }

    public long getRoomTypeId() {
        return roomTypeId;
    }

    public void setRoomTypeId(long roomTypeId) {
        this.roomTypeId = roomTypeId;
    }

    public Long getID() {
        return ID;
    }

    public void setID(Long id) {
        ID = id;
    }

    public String getAddType() {
        return addType;
    }

    public void setAddType(String addType) {
        this.addType = addType;
    }

    public long getPriceTypeId() {
        return priceTypeId;
    }

    public void setPriceTypeId(long priceTypeId) {
        this.priceTypeId = priceTypeId;
    }

}