package com.mangocity.hotel.base.persistence;

import com.mangocity.util.Entity;

/**
 * HtlAssureItemEverydayBatch generated by MyEclipse Persistence Tools
 */

public class HtlAssureItemEverydayBatch extends CEntity implements Entity {

    // Fields

    private Long id;

    private HtlAssureBatch htlAssureBatch;

    private String type;

    private String firstDateOrDays;

    private String firstTime;

    private String secondDateOrDays;

    private String secondTime;

    private String scope;

    private String deductType;

    private String percentage;

    private String beforeorafter;

    public String getBeforeorafter() {
        return beforeorafter;
    }

    public void setBeforeorafter(String beforeorafter) {
        this.beforeorafter = beforeorafter;
    }

    /** default constructor */
    public HtlAssureItemEverydayBatch() {
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public HtlAssureBatch getHtlAssureBatch() {
        return htlAssureBatch;
    }

    public void setHtlAssureBatch(HtlAssureBatch htlAssureBatch) {
        this.htlAssureBatch = htlAssureBatch;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getFirstDateOrDays() {
        return this.firstDateOrDays;
    }

    public void setFirstDateOrDays(String firstDateOrDays) {
        this.firstDateOrDays = firstDateOrDays;
    }

    public String getFirstTime() {
        return this.firstTime;
    }

    public void setFirstTime(String firstTime) {
        this.firstTime = firstTime;
    }

    public String getSecondDateOrDays() {
        return this.secondDateOrDays;
    }

    public void setSecondDateOrDays(String secondDateOrDays) {
        this.secondDateOrDays = secondDateOrDays;
    }

    public String getSecondTime() {
        return this.secondTime;
    }

    public void setSecondTime(String secondTime) {
        this.secondTime = secondTime;
    }

    public String getScope() {
        return this.scope;
    }

    public void setScope(String scope) {
        this.scope = scope;
    }

    public String getDeductType() {
        return this.deductType;
    }

    public void setDeductType(String deductType) {
        this.deductType = deductType;
    }

    public String getPercentage() {
        return this.percentage;
    }

    public void setPercentage(String percentage) {
        this.percentage = percentage;
    }

    public Long getID() {
        // TODO Auto-generated method stub
        return id;
    }

}