package com.mangocity.hotel.base.persistence;

import java.util.ArrayList;
import java.util.List;

import com.mangocity.util.Entity;

/**
 * 担保条款 add by shengwei.zuo HtlAssure generated by MyEclipse Persistence Tools
 */

public class HtlAssure extends CEntity implements Entity {

    // Fields

    /**
	 * 
	 */

    private Long id;

    private String isNotConditional;

    private String latestAssureTime;

    private Long overRoomNumber;

    private Long overNightsNumber;

    private String assureType;

    private String assureLetter;

    /*
     * add by shengwei.zuo 2009-02-10 酒店预订担保预付条款总表
     */
    private HtlPreconcertItem htlPreconcertItem;

    /**
     * 每日的担保修改取消条款
     */
    private List<HtlAssureItemEveryday> htlAssureItemEverydayList;

    private List<HtlAssureItemTemplateOne> lisHtlAssureItemTemplateOne = 
        new ArrayList<HtlAssureItemTemplateOne>();

    private List<HtlAssureItemTemplateTwo> lisHtlAssureItemTemplateTwo = 
        new ArrayList<HtlAssureItemTemplateTwo>();

    private List<HtlAssureItemTemplateThree> lisHtlAssureItemTemplateThree = 
        new ArrayList<HtlAssureItemTemplateThree>();

    private List<HtlAssureItemTemplateFour> lisHtlAssureItemTemplateFour = 
        new ArrayList<HtlAssureItemTemplateFour>();

    private List<HtlAssureItemTemplateFive> lisHtlAssureItemTemplateFive = 
        new ArrayList<HtlAssureItemTemplateFive>();

    // Constructors

    /** default constructor */
    public HtlAssure() {
    }

    /** full constructor */
    public HtlAssure(String isNotConditional, String latestAssureTime, Long overRoomNumber,
        String assureType, String assureLetter) {
        this.isNotConditional = isNotConditional;
        this.latestAssureTime = latestAssureTime;
        this.overRoomNumber = overRoomNumber;
        this.assureType = assureType;
        this.assureLetter = assureLetter;
    }

    // Property accessors

    public String getIsNotConditional() {
        return this.isNotConditional;
    }

    public void setIsNotConditional(String isNotConditional) {
        this.isNotConditional = isNotConditional;
    }

    public String getLatestAssureTime() {
        return this.latestAssureTime;
    }

    public void setLatestAssureTime(String latestAssureTime) {
        this.latestAssureTime = latestAssureTime;
    }

    public Long getOverRoomNumber() {
        return this.overRoomNumber;
    }

    public void setOverRoomNumber(Long overRoomNumber) {
        this.overRoomNumber = overRoomNumber;
    }

    public String getAssureType() {
        return this.assureType;
    }

    public void setAssureType(String assureType) {
        this.assureType = assureType;
    }

    public String getAssureLetter() {
        return this.assureLetter;
    }

    public void setAssureLetter(String assureLetter) {
        this.assureLetter = assureLetter;
    }

    public List<HtlAssureItemEveryday> getHtlAssureItemEverydayList() {
        return htlAssureItemEverydayList;
    }

    public void setHtlAssureItemEverydayList(List<HtlAssureItemEveryday> htlAssureItemEverydayList) {
        this.htlAssureItemEverydayList = htlAssureItemEverydayList;
    }

    public HtlPreconcertItem getHtlPreconcertItem() {
        return htlPreconcertItem;
    }

    public void setHtlPreconcertItem(HtlPreconcertItem htlPreconcertItem) {
        this.htlPreconcertItem = htlPreconcertItem;
    }

    public List<HtlAssureItemTemplateFive> getLisHtlAssureItemTemplateFive() {
        return lisHtlAssureItemTemplateFive;
    }

    public void setLisHtlAssureItemTemplateFive(
        List<HtlAssureItemTemplateFive> lisHtlAssureItemTemplateFive) {
        this.lisHtlAssureItemTemplateFive = lisHtlAssureItemTemplateFive;
    }

    public List<HtlAssureItemTemplateFour> getLisHtlAssureItemTemplateFour() {
        return lisHtlAssureItemTemplateFour;
    }

    public void setLisHtlAssureItemTemplateFour(
        List<HtlAssureItemTemplateFour> lisHtlAssureItemTemplateFour) {
        this.lisHtlAssureItemTemplateFour = lisHtlAssureItemTemplateFour;
    }

    public List<HtlAssureItemTemplateOne> getLisHtlAssureItemTemplateOne() {
        return lisHtlAssureItemTemplateOne;
    }

    public void setLisHtlAssureItemTemplateOne(
        List<HtlAssureItemTemplateOne> lisHtlAssureItemTemplateOne) {
        this.lisHtlAssureItemTemplateOne = lisHtlAssureItemTemplateOne;
    }

    public List<HtlAssureItemTemplateThree> getLisHtlAssureItemTemplateThree() {
        return lisHtlAssureItemTemplateThree;
    }

    public void setLisHtlAssureItemTemplateThree(
        List<HtlAssureItemTemplateThree> lisHtlAssureItemTemplateThree) {
        this.lisHtlAssureItemTemplateThree = lisHtlAssureItemTemplateThree;
    }

    public List<HtlAssureItemTemplateTwo> getLisHtlAssureItemTemplateTwo() {
        return lisHtlAssureItemTemplateTwo;
    }

    public void setLisHtlAssureItemTemplateTwo(
        List<HtlAssureItemTemplateTwo> lisHtlAssureItemTemplateTwo) {
        this.lisHtlAssureItemTemplateTwo = lisHtlAssureItemTemplateTwo;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getID() {
        // TODO Auto-generated method stub
        return id;
    }

    public Long getOverNightsNumber() {
        return overNightsNumber;
    }

    public void setOverNightsNumber(Long overNightsNumber) {
        this.overNightsNumber = overNightsNumber;
    }

}