package com.mangocity.hotel.base.persistence;

import java.util.Date;

import com.mangocity.util.Entity;

/**
 * HtlAssureItemTemplate generated by MyEclipse Persistence Tools 担保取消修改条款模板
 */

public class HtlAssureItemTemplate extends CEntity implements Entity {

    // Fields

    private Long id;

    /*
     * 担保条款ID
     */
    private Long assureClauseId;

    /*
     * 取消修改条款种类
     */
    private String type;

    /*
     * 第一日期或天数
     */

    private String firstDateOrDays;

    /*
     * 第一时间点
     */
    private String firstTime;

    /*
     * 第二日期或天数
     */
    private String secondDateOrDays;

    /*
     * 第二时间点
     */

    private String secondTime;

    /*
     * 取消修改范围
     */

    private String scope;

    /*
     * 
     * 扣款类型
     */

    private String deductType;

    /*
     * 扣款百分比
     */
    private String percentage;

    /*
     * 之前还是之后
     */
    private String beforeOrAfter;

    private Date firstDate;// 用于在页面中转换日期的变量 第一日期

    private Date secondDate;// 第二日期

    private HtlAssureTemplate htlAssureTemplate;

    // Constructors

    /** default constructor */
    public HtlAssureItemTemplate() {
    }

    /** full constructor */
    public HtlAssureItemTemplate(Long assureClauseId, String type, String firstDateOrDays,
        String firstTime, String secondDateOrDays, String secondTime, String scope,
        String deductType, String percentage) {
        this.assureClauseId = assureClauseId;
        this.type = type;
        this.firstDateOrDays = firstDateOrDays;
        this.firstTime = firstTime;
        this.secondDateOrDays = secondDateOrDays;
        this.secondTime = secondTime;
        this.scope = scope;
        this.deductType = deductType;
        this.percentage = percentage;
    }

    // Property accessors

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAssureClauseId() {
        return this.assureClauseId;
    }

    public void setAssureClauseId(Long assureClauseId) {
        this.assureClauseId = assureClauseId;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
    	if(null == type){
    		this.type="";
    	}else{
    		 this.type = type;
    	}
    }

    public String getFirstDateOrDays() {
        return this.firstDateOrDays;
    }

    public void setFirstDateOrDays(String firstDateOrDays) {
        this.firstDateOrDays = firstDateOrDays;
    }

    public String getFirstTime() {
        return this.firstTime;
    }

    public void setFirstTime(String firstTime) {
        this.firstTime = firstTime;
    }

    public String getSecondDateOrDays() {
        return this.secondDateOrDays;
    }

    public void setSecondDateOrDays(String secondDateOrDays) {
        this.secondDateOrDays = secondDateOrDays;
    }

    public String getSecondTime() {
        return this.secondTime;
    }

    public void setSecondTime(String secondTime) {
        this.secondTime = secondTime;
    }

    public String getScope() {
        return this.scope;
    }

    public void setScope(String scope) {
        this.scope = scope;
    }

    public String getDeductType() {
        return this.deductType;
    }

    public void setDeductType(String deductType) {
        this.deductType = deductType;
    }

    public String getPercentage() {
        return this.percentage;
    }

    public void setPercentage(String percentage) {
        this.percentage = percentage;
    }

    public Long getID() {
        // TODO Auto-generated method stub
        return id;
    }

    public HtlAssureTemplate getHtlAssureTemplate() {
        return htlAssureTemplate;
    }

    public void setHtlAssureTemplate(HtlAssureTemplate htlAssureTemplate) {
        this.htlAssureTemplate = htlAssureTemplate;
    }

    public String getBeforeOrAfter() {
        return beforeOrAfter;
    }

    public void setBeforeOrAfter(String beforeOrAfter) {
        this.beforeOrAfter = beforeOrAfter;
    }

    public Date getFirstDate() {
        return firstDate;
    }

    public void setFirstDate(Date firstDate) {
        this.firstDate = firstDate;
    }

    public Date getSecondDate() {
        return secondDate;
    }

    public void setSecondDate(Date secondDate) {
        this.secondDate = secondDate;
    }

}