package com.mangocity.hotel.base.persistence;

import java.util.Date;
import java.util.List;

/**
 * HtlEbookingPersonnelInfo generated by MyEclipse Persistence Tools
 */

public class HtlEbookingPersonnelInfo implements java.io.Serializable {

	// Fields

	private Long personnelid;

	private String hotelname;

	private String hotelid;

	private String loginname;

	private String loginpass;

	private String name;

	private String deptname;

	private String telephone;

	private String mobileno;

	private String email;

	private Long personnelvalidity;

	private String tempfunctionname;

	private String operationer;

	private Date operationdate;

	private String operationerid;

	private Long state;
	
	private Long superper;
	
	private Long loginamo;
	
	private List functionMasters;

	// Constructors

	public List getFunctionMasters() {
		return functionMasters;
	}

	public void setFunctionMasters(List functionMasters) {
		this.functionMasters = functionMasters;
	}

	/** default constructor */
	public HtlEbookingPersonnelInfo() {
	}

	/** minimal constructor */
	public HtlEbookingPersonnelInfo(Long personnelid, String hotelname,
			String hotelid, String loginname, String loginpass, String name,
			String deptname, Long personnelvalidity, String operationer) {
		this.personnelid = personnelid;
		this.hotelname = hotelname;
		this.hotelid = hotelid;
		this.loginname = loginname;
		this.loginpass = loginpass;
		this.name = name;
		this.deptname = deptname;
		this.personnelvalidity = personnelvalidity;
		this.operationer = operationer;
	}

	/** full constructor */
	public HtlEbookingPersonnelInfo(Long personnelid, String hotelname,
			String hotelid, String loginname, String loginpass, String name,
			String deptname, String telephone, String mobileno, String email,
			Long personnelvalidity, String tempfunctionname,
			String operationer, Date operationdate, String operationerid,
			Long state, Long superper, Long loginamo) {
		this.personnelid = personnelid;
		this.hotelname = hotelname;
		this.hotelid = hotelid;
		this.loginname = loginname;
		this.loginpass = loginpass;
		this.name = name;
		this.deptname = deptname;
		this.telephone = telephone;
		this.mobileno = mobileno;
		this.email = email;
		this.personnelvalidity = personnelvalidity;
		this.tempfunctionname = tempfunctionname;
		this.operationer = operationer;
		this.operationdate = operationdate;
		this.operationerid = operationerid;
		this.state = state;
		this.superper = superper;
		this.loginamo = loginamo;
	}

	// Property accessors

	public Long getPersonnelid() {
		return this.personnelid;
	}

	public void setPersonnelid(Long personnelid) {
		this.personnelid = personnelid;
	}

	public String getHotelname() {
		return this.hotelname;
	}

	public void setHotelname(String hotelname) {
		this.hotelname = hotelname;
	}

	public String getHotelid() {
		return this.hotelid;
	}

	public void setHotelid(String hotelid) {
		this.hotelid = hotelid;
	}

	public String getLoginname() {
		return this.loginname;
	}

	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	public String getLoginpass() {
		return this.loginpass;
	}

	public void setLoginpass(String loginpass) {
		this.loginpass = loginpass;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDeptname() {
		return this.deptname;
	}

	public void setDeptname(String deptname) {
		this.deptname = deptname;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getMobileno() {
		return this.mobileno;
	}

	public void setMobileno(String mobileno) {
		this.mobileno = mobileno;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Long getPersonnelvalidity() {
		return this.personnelvalidity;
	}

	public void setPersonnelvalidity(Long personnelvalidity) {
		this.personnelvalidity = personnelvalidity;
	}

	public String getTempfunctionname() {
		return this.tempfunctionname;
	}

	public void setTempfunctionname(String tempfunctionname) {
		this.tempfunctionname = tempfunctionname;
	}

	public String getOperationer() {
		return this.operationer;
	}

	public void setOperationer(String operationer) {
		this.operationer = operationer;
	}

	public Date getOperationdate() {
		return this.operationdate;
	}

	public void setOperationdate(Date operationdate) {
		this.operationdate = operationdate;
	}

	public String getOperationerid() {
		return this.operationerid;
	}

	public void setOperationerid(String operationerid) {
		this.operationerid = operationerid;
	}

	public Long getState() {
		return this.state;
	}

	public void setState(Long state) {
		this.state = state;
	}

	public Long getSuperper() {
		return superper;
	}

	public void setSuperper(Long superper) {
		this.superper = superper;
	}

	public Long getLoginamo() {
		return loginamo;
	}

	public void setLoginamo(Long loginamo) {
		this.loginamo = loginamo;
	}

}