package com.mangocity.hotel.base.persistence;

/**
 * HtlRoomcontrolOptsublogs generated by MyEclipse Persistence Tools
 */

public class HtlHessianIpcontrol implements java.io.Serializable {
	//主键key 
	private Long id;
	
	//允许访问的ip地址
	private String ip;

	//端口号
	private Long port;
	
	//属于哪个项目
	private String owner;
	
	//数据有效性
	private String status;
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getIp() {
		return ip;
	}
	public void setIp(String ip) {
		this.ip = ip;
	}
	public Long getPort() {
		return port;
	}
	public void setPort(Long port) {
		this.port = port;
	}
	public String getOwner() {
		return owner;
	}
	public void setOwner(String owner) {
		this.owner = owner;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}

	
}