package com.mangocity.hotel.base.persistence;

import java.util.Date;

import com.mangocity.util.Entity;

/**
 * HtlAddscope generated by MyEclipse - Hibernate Tools
 */

public class HtlHdlAddscope extends CEntity implements Entity {

    /**
     * 加幅id
     */
    private Long ID;

    /**
     * 酒店id
     */
    private long hotelId;

    /**
     * 加幅开始日期
     */
    private Date beginDate;

    /**
     * 加幅结束日期
     */
    private Date endDate;

    /**
     * 所有勾选的价格类型ID，之间用逗号隔开
     */
    private String allPriceTypeId;

    /**
     * 所有勾选的房型及价格类型名称，之间用逗号隔开，在hibernate不定义，只用作页面显示
     */
    private String roomNamePriceName;

    /**
     * <1的值表示加幅比率 >＝1表示加幅金额
     */
    private long addScope;

    /**
     * 加幅金额的币种（默认为该酒店的结算币种)
     */
    private String currency;

    /** default constructor */
    public HtlHdlAddscope() {
    }

    public long getAddScope() {
        return addScope;
    }

    public void setAddScope(long addScope) {
        this.addScope = addScope;
    }

    public String getAllPriceTypeId() {
        return allPriceTypeId;
    }

    public void setAllPriceTypeId(String allPriceTypeId) {
        this.allPriceTypeId = allPriceTypeId;
    }

    public Date getBeginDate() {
        return beginDate;
    }

    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public Date getEndDate() {
        return endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public long getHotelId() {
        return hotelId;
    }

    public void setHotelId(long hotelId) {
        this.hotelId = hotelId;
    }

    public Long getID() {
        return ID;
    }

    public void setID(Long id) {
        ID = id;
    }

    public String getRoomNamePriceName() {
        return roomNamePriceName;
    }

    public void setRoomNamePriceName(String roomNamePriceName) {
        this.roomNamePriceName = roomNamePriceName;
    }

}