package com.mangocity.hotel.base.persistence;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.mangocity.util.Entity;

/**
 * HtlPrepayEveryday generated by MyEclipse Persistence Tools
 */

public class HtlPrepayEveryday extends CEntity implements Entity {

    // Fields

    private Long id;

    private String balanceType;

    private String paymentType;

    private String amountType;

    private Date limitDate;

    private String limitTime;

    private Long limitAheadDays;

    private String limitAheadDaysTime;

    private Long daysAfterConfirm;

    private String timeAfterConfirm;

    private String timeLimitType;

    private String prepayDeductType;

    private HtlPreconcertItem htlPreconcertItem;

    /**
     * 每日的预付修改取消条款
     */
    private List<HtlPrepayItemEveryday> htlPrepayItemEverydayList;

    private List<HtlPrepayItemTemplateOne> lisHtlPrepayItemTemplateOne = 
        new ArrayList<HtlPrepayItemTemplateOne>();

    private List<HtlPrepayItemTemplateTwo> lisHtlPrepayItemTemplateTwo = 
        new ArrayList<HtlPrepayItemTemplateTwo>();

    private List<HtlPrepayItemTemplateThree> lisHtlPrepayItemTemplateThree = 
        new ArrayList<HtlPrepayItemTemplateThree>();

    private List<HtlPrepayItemTemplateFour> lisHtlPrepayItemTemplateFour = 
        new ArrayList<HtlPrepayItemTemplateFour>();

    private List<HtlPrepayItemTemplateFive> lisHtlPrepayItemTemplateFive = 
        new ArrayList<HtlPrepayItemTemplateFive>();

    // Constructors

    /** default constructor */
    public HtlPrepayEveryday() {
    }

    /** full constructor */
    public HtlPrepayEveryday(String balanceType, String paymentType, String amountType,
        Date limitDate, String limitTime, Long limitAheadDays, String limitAheadDaysTime,
        Long daysAfterConfirm, String timeAfterConfirm) {
        this.balanceType = balanceType;
        this.paymentType = paymentType;
        this.amountType = amountType;
        this.limitDate = limitDate;
        this.limitTime = limitTime;
        this.limitAheadDays = limitAheadDays;
        this.limitAheadDaysTime = limitAheadDaysTime;
        this.daysAfterConfirm = daysAfterConfirm;
        this.timeAfterConfirm = timeAfterConfirm;
    }

    // Property accessors

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBalanceType() {
        return this.balanceType;
    }

    public void setBalanceType(String balanceType) {
        this.balanceType = balanceType;
    }

    public String getPaymentType() {
        return this.paymentType;
    }

    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType;
    }

    public String getAmountType() {
        return this.amountType;
    }

    public void setAmountType(String amountType) {
        this.amountType = amountType;
    }

    public Date getLimitDate() {
        return this.limitDate;
    }

    public void setLimitDate(Date limitDate) {
        this.limitDate = limitDate;
    }

    public String getLimitTime() {
        return this.limitTime;
    }

    public void setLimitTime(String limitTime) {
        this.limitTime = limitTime;
    }

    public Long getLimitAheadDays() {
        return this.limitAheadDays;
    }

    public void setLimitAheadDays(Long limitAheadDays) {
        this.limitAheadDays = limitAheadDays;
    }

    public String getLimitAheadDaysTime() {
        return this.limitAheadDaysTime;
    }

    public void setLimitAheadDaysTime(String limitAheadDaysTime) {
        this.limitAheadDaysTime = limitAheadDaysTime;
    }

    public Long getDaysAfterConfirm() {
        return this.daysAfterConfirm;
    }

    public void setDaysAfterConfirm(Long daysAfterConfirm) {
        this.daysAfterConfirm = daysAfterConfirm;
    }

    public String getTimeAfterConfirm() {
        return this.timeAfterConfirm;
    }

    public void setTimeAfterConfirm(String timeAfterConfirm) {
        this.timeAfterConfirm = timeAfterConfirm;
    }

    public HtlPreconcertItem getHtlPreconcertItem() {
        return htlPreconcertItem;
    }

    public void setHtlPreconcertItem(HtlPreconcertItem htlPreconcertItem) {
        this.htlPreconcertItem = htlPreconcertItem;
    }

    public String getTimeLimitType() {
        return timeLimitType;
    }

    public void setTimeLimitType(String timeLimitType) {
        this.timeLimitType = timeLimitType;
    }

    public Long getID() {
        // TODO Auto-generated method stub
        return id;
    }

    public List<HtlPrepayItemEveryday> getHtlPrepayItemEverydayList() {
        return htlPrepayItemEverydayList;
    }

    public void setHtlPrepayItemEverydayList(List<HtlPrepayItemEveryday> htlPrepayItemEverydayList) {
        this.htlPrepayItemEverydayList = htlPrepayItemEverydayList;
    }

    public List<HtlPrepayItemTemplateFive> getLisHtlPrepayItemTemplateFive() {
        return lisHtlPrepayItemTemplateFive;
    }

    public void setLisHtlPrepayItemTemplateFive(
        List<HtlPrepayItemTemplateFive> lisHtlPrepayItemTemplateFive) {
        this.lisHtlPrepayItemTemplateFive = lisHtlPrepayItemTemplateFive;
    }

    public List<HtlPrepayItemTemplateFour> getLisHtlPrepayItemTemplateFour() {
        return lisHtlPrepayItemTemplateFour;
    }

    public void setLisHtlPrepayItemTemplateFour(
        List<HtlPrepayItemTemplateFour> lisHtlPrepayItemTemplateFour) {
        this.lisHtlPrepayItemTemplateFour = lisHtlPrepayItemTemplateFour;
    }

    public List<HtlPrepayItemTemplateOne> getLisHtlPrepayItemTemplateOne() {
        return lisHtlPrepayItemTemplateOne;
    }

    public void setLisHtlPrepayItemTemplateOne(
        List<HtlPrepayItemTemplateOne> lisHtlPrepayItemTemplateOne) {
        this.lisHtlPrepayItemTemplateOne = lisHtlPrepayItemTemplateOne;
    }

    public List<HtlPrepayItemTemplateThree> getLisHtlPrepayItemTemplateThree() {
        return lisHtlPrepayItemTemplateThree;
    }

    public void setLisHtlPrepayItemTemplateThree(
        List<HtlPrepayItemTemplateThree> lisHtlPrepayItemTemplateThree) {
        this.lisHtlPrepayItemTemplateThree = lisHtlPrepayItemTemplateThree;
    }

    public List<HtlPrepayItemTemplateTwo> getLisHtlPrepayItemTemplateTwo() {
        return lisHtlPrepayItemTemplateTwo;
    }

    public void setLisHtlPrepayItemTemplateTwo(
        List<HtlPrepayItemTemplateTwo> lisHtlPrepayItemTemplateTwo) {
        this.lisHtlPrepayItemTemplateTwo = lisHtlPrepayItemTemplateTwo;
    }

    public String getPrepayDeductType() {
        return prepayDeductType;
    }

    public void setPrepayDeductType(String prepayDeductType) {
        this.prepayDeductType = prepayDeductType;
    }

}