package com.mangocity.hotel.base.persistence;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * HtlPreconcertItemBatch generated by MyEclipse Persistence Tools
 */

public class HtlPreconcertItemBatch extends CEntity implements java.io.Serializable {

    // Fields

    private Long id;

    private Long hotelId;

    private Long reservationTemplateId;

    private String reservationName;

    private Long contractId;

    private Date validDate;

    private Long priceTypeId;

    private String payToPrepay;

    private String attention;

    private String createBy;

    private String createById;

    private Date createTime;

    private String modifyBy;

    private String modifyById;

    private Date modifyTime;

    private String delBy;

    private String delById;

    private Date delTime;

    private String active;

    private Date beginDate;

    private Date endDate;

    private String updateFalg;

    private String doubletofalg;

    private String weeks;

    private List<HtlAssureBatch> htlAssureBatch = new ArrayList<HtlAssureBatch>();

    private List htlPrepayEverydayBatch;

    private List htlReservationBatch;

    // Constructors

    public List getHtlPrepayEverydayBatch() {
        return htlPrepayEverydayBatch;
    }

    public void setHtlPrepayEverydayBatch(List htlPrepayEverydayBatch) {
        this.htlPrepayEverydayBatch = htlPrepayEverydayBatch;
    }

    public List getHtlReservationBatch() {
        return htlReservationBatch;
    }

    public void setHtlReservationBatch(List htlReservationBatch) {
        this.htlReservationBatch = htlReservationBatch;
    }

    /** default constructor */
    public HtlPreconcertItemBatch() {
    }

    // Property accessors

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getHotelId() {
        return this.hotelId;
    }

    public void setHotelId(Long hotelId) {
        this.hotelId = hotelId;
    }

    public Long getReservationTemplateId() {
        return this.reservationTemplateId;
    }

    public void setReservationTemplateId(Long reservationTemplateId) {
        this.reservationTemplateId = reservationTemplateId;
    }

    public String getReservationName() {
        return this.reservationName;
    }

    public void setReservationName(String reservationName) {
        this.reservationName = reservationName;
    }

    public Long getContractId() {
        return this.contractId;
    }

    public void setContractId(Long contractId) {
        this.contractId = contractId;
    }

    public Date getValidDate() {
        return this.validDate;
    }

    public void setValidDate(Date validDate) {
        this.validDate = validDate;
    }

    public Long getPriceTypeId() {
        return this.priceTypeId;
    }

    public void setPriceTypeId(Long priceTypeId) {
        this.priceTypeId = priceTypeId;
    }

    public String getPayToPrepay() {
        return this.payToPrepay;
    }

    public void setPayToPrepay(String payToPrepay) {
        this.payToPrepay = payToPrepay;
    }

    public String getAttention() {
        return this.attention;
    }

    public void setAttention(String attention) {
        this.attention = attention;
    }

    public String getCreateBy() {
        return this.createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    public String getCreateById() {
        return this.createById;
    }

    public void setCreateById(String createById) {
        this.createById = createById;
    }

    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getModifyBy() {
        return this.modifyBy;
    }

    public void setModifyBy(String modifyBy) {
        this.modifyBy = modifyBy;
    }

    public String getModifyById() {
        return this.modifyById;
    }

    public void setModifyById(String modifyById) {
        this.modifyById = modifyById;
    }

    public Date getModifyTime() {
        return this.modifyTime;
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public String getDelBy() {
        return this.delBy;
    }

    public void setDelBy(String delBy) {
        this.delBy = delBy;
    }

    public String getDelById() {
        return this.delById;
    }

    public void setDelById(String delById) {
        this.delById = delById;
    }

    public Date getDelTime() {
        return this.delTime;
    }

    public void setDelTime(Date delTime) {
        this.delTime = delTime;
    }

    public String getActive() {
        return this.active;
    }

    public void setActive(String active) {
        this.active = active;
    }

    public Date getBeginDate() {
        return this.beginDate;
    }

    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }

    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public String getUpdateFalg() {
        return this.updateFalg;
    }

    public void setUpdateFalg(String updateFalg) {
        this.updateFalg = updateFalg;
    }

    public String getDoubletofalg() {
        return this.doubletofalg;
    }

    public void setDoubletofalg(String doubletofalg) {
        this.doubletofalg = doubletofalg;
    }

    public List<HtlAssureBatch> getHtlAssureBatch() {
        return htlAssureBatch;
    }

    public void setHtlAssureBatch(List<HtlAssureBatch> htlAssureBatch) {
        this.htlAssureBatch = htlAssureBatch;
    }

    public String getWeeks() {
        return weeks;
    }

    public void setWeeks(String weeks) {
        this.weeks = weeks;
    }

}