package com.mangocity.hotel.base.persistence;

import java.util.Date;

import com.mangocity.util.Entity;

/**
 * HtlPrepayItemTemplate generated by MyEclipse Persistence Tools 预付取消及修改条款模板
 */

public class HtlPrepayItemTemplate extends CEntity implements Entity {

    // Fields

    private Long id;

    private HtlPrepayTemplate htlPrepayTemplate;

    private String type;

    private String firstDateOrDays;

    private String firstTime;

    private String secondDateOrDays;

    private String secondTime;

    private String scope;

    private String deductType;

    private String percentage;

    private String beforeOrAfter;

    private Date firstDate;// 用于在页面中转换日期的变量 第一日期

    private Date secondDate;// 第二日期

    // Constructors

    public Date getFirstDate() {
        return firstDate;
    }

    public void setFirstDate(Date firstDate) {
        this.firstDate = firstDate;
    }

    public Date getSecondDate() {
        return secondDate;
    }

    public void setSecondDate(Date secondDate) {
        this.secondDate = secondDate;
    }

    public String getBeforeOrAfter() {
        return beforeOrAfter;
    }

    public void setBeforeOrAfter(String beforeOrAfter) {
        this.beforeOrAfter = beforeOrAfter;
    }

    /** default constructor */
    public HtlPrepayItemTemplate() {
    }

    // Property accessors

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public HtlPrepayTemplate getHtlPrepayTemplate() {
        return htlPrepayTemplate;
    }

    public void setHtlPrepayTemplate(HtlPrepayTemplate htlPrepayTemplate) {
        this.htlPrepayTemplate = htlPrepayTemplate;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
    	if(null == type){
    		this.type="";
    	}else{
    		 this.type = type;
    	}
    }

    public String getFirstDateOrDays() {
        return this.firstDateOrDays;
    }

    public void setFirstDateOrDays(String firstDateOrDays) {
        this.firstDateOrDays = firstDateOrDays;
    }

    public String getFirstTime() {
        return this.firstTime;
    }

    public void setFirstTime(String firstTime) {
        this.firstTime = firstTime;
    }

    public String getSecondDateOrDays() {
        return this.secondDateOrDays;
    }

    public void setSecondDateOrDays(String secondDateOrDays) {
        this.secondDateOrDays = secondDateOrDays;
    }

    public String getSecondTime() {
        return this.secondTime;
    }

    public void setSecondTime(String secondTime) {
        this.secondTime = secondTime;
    }

    public String getScope() {
        return this.scope;
    }

    public void setScope(String scope) {
        this.scope = scope;
    }

    public String getDeductType() {
        return this.deductType;
    }

    public void setDeductType(String deductType) {
        this.deductType = deductType;
    }

    public String getPercentage() {
        return this.percentage;
    }

    public void setPercentage(String percentage) {
        this.percentage = percentage;
    }

    public Long getID() {
        // TODO Auto-generated method stub
        return id;
    }

}