package com.mangocity.hotel.base.persistence;

import com.mangocity.util.Entity;

/**
 * HtlWelcomePrice generated by MyEclipse - Hibernate Tools
 */

public class HtlPriceType extends CEntity implements Entity {

    // Fields

    private Long ID;

    /**
     * 房型
     */
    private HtlRoomtype roomType;

    /**
     *价格类型
     */
    private String priceType;
    
    /**
     *added by xie yanhui 2011-07-19 价格类型多渠道预定，如CC/WEB/B2B/114
     */
    private Long multi_channel;
    
    /**
     *added by xie yanhui 2011-08-29 价格类型供应商，用于多渠道发送传真用
     */
    private Long supplierID;

    /**
     * 这个字段不保存在数据中，只在页面显示用.
     */
    private Long keyId;

    /**
     * 价格类型编码
     */
    private String pricetypeCodeName;
    
    private Boolean showMemberPrice;

    public HtlPriceType() {

    }

    public Long getID() {
        return ID;
    }

    public void setID(Long id) {
        ID = id;
    }

    public String getPriceType() {
        return priceType;
    }

    public void setPriceType(String priceType) {
        this.priceType = priceType;
    }

    public HtlRoomtype getRoomType() {
        return roomType;
    }

    public void setRoomType(HtlRoomtype roomType) {
        this.roomType = roomType;
    }

    public Long getKeyId() {
        return keyId;
    }

    public void setKeyId(Long keyId) {
        this.keyId = keyId;
    }

    public String getPricetypeCodeName() {
        return pricetypeCodeName;
    }

    public void setPricetypeCodeName(String pricetypeCodeName) {
        this.pricetypeCodeName = pricetypeCodeName;
    }

	public Long getMulti_channel() {
		return multi_channel;
	}

	public void setMulti_channel(Long multi_channel) {
		this.multi_channel = multi_channel;
	}

	public Long getSupplierID() {
		return supplierID;
	}

	public void setSupplierID(Long supplierID) {
		this.supplierID = supplierID;
	}

	public Boolean getShowMemberPrice() {
		return showMemberPrice;
	}

	public void setShowMemberPrice(Boolean showMemberPrice) {
		this.showMemberPrice = showMemberPrice;
	}

	
}