package com.mangocity.hotel.base.persistence;

import java.util.Date;

import com.mangocity.util.Entity;

/**
 * HtlQuotaNew generated by MyEclipse Persistence Tools 配额总表
 */

public class HtlQuotaNew implements Entity {

    // Fields
    /**
     * 配额ID
     */
    private Long ID;

    /**
     * 有效的可卖日期
     */
    private Date ableSaleDate;

    /**
     * 酒店ID
     */
    private Long hotelId;

    /**
     * 房型ID
     */
    private Long roomtypeId;

    /**
     * 床型ID
     */
    private Long bedId;

    /**
     * 配额所有者（指：TMC、套票、CC等）
     */
    private String quotaHolder;

    /**
     * 配额共享模式（面付、预付、独占）
     */
    private Long quotaShareType;

    /**
     * 包房配额总数
     */
    private Long buyQuotaSum;

    /**
     * 包房配额可用数
     */
    private Long buyQuotaAbleNum;

    /**
     * 包房配额已用数
     */
    private Long buyQuotaUsedNum;

    /**
     * 包房配额过期数
     */
    private Long buyQuotaOutofdateNum;

    /**
     * 普通配额总数
     */
    private Long commonQuotaSum;

    /**
     * 普通配额可用数
     */
    private Long commonQuotaAbleNum;

    /**
     * 普通配额已用数
     */
    private Long commonQuotaUsedNum;

    /**
     * 普通配额过期数
     */
    private Long commonQuotaOutofdateNum;

    /**
     * 呼出配额数
     */
    private Long outsideQuotaSum;

    /**
     * 临时配额总数
     */
    private Long casualQuotaSum;

    /**
     * 临时配额可用数
     */
    private Long casualQuotaAbleNum;

    /**
     * 临时配额已用数
     */
    private Long casualQuotaUsedNum;

    /**
     * 临时配额过期数
     */
    private Long casualQuotaOutofdateNum;

    /**
     * 配额预警数
     */
    private Long forewarnQuotaNum;

    /**
     * 配额预警标识
     */
    private Long forewarnFlag;

    /**
     * 创建部门
     */
    private String createDept;

    /**
     * 创建者ID
     */
    private String createId;

    /**
     * 创建者姓名
     */
    private String createName;

    /**
     * 创建日期
     */
    private Date createDate;

    /**
     * 修改部门
     */
    private String modifyDept;

    /**
     * 修改者ID
     */
    private String modifyId;

    /**
     * 修改者姓名
     */
    private String modifyName;

    /**
     * 修改日期
     */
    private Date modifyDate;

    /**
     * 是否需要预警，主要是解决预警数量为0时,
     * 0表示不需要预警，只要大于0就表示一定要预警
     */
    private Long forewarnYesOrNo;
    
    
    /**
     * 可用配额总数  add by shengwei.zuo
     * @return
     */
    private Integer canUserQuotaNum;
    
    private String quotaPattern;
    
    // Constructors

    /** default constructor */
    public HtlQuotaNew() {
    }

    /** minimal constructor */
    public HtlQuotaNew(Long htlQuotaNewId) {
        this.ID = htlQuotaNewId;
    }

    /** full constructor */
    public HtlQuotaNew(Long htlQuotaNewId, Date ableSaleDate, Long hotelId, Long roomtypeId,
        Long bedId, String quotaHolder, Long quotaShareType, Long buyQuotaSum,
        Long buyQuotaAbleNum, Long buyQuotaUsedNum, Long buyQuotaOutofdateNum, Long commonQuotaSum,
        Long commonQuotaAbleNum, Long commonQuotaUsedNum, Long commonQuotaOutofdateNum,
        Long outsideQuotaSum, Long casualQuotaSum, Long casualQuotaAbleNum,
        Long casualQuotaUsedNum, Long casualQuotaOutofdateNum, Long forewarnQuotaNum,
        Long forewarnFlag, String createDept, String createId, String createName, Date createDate,
        String modifyDept, String modifyId, String modifyName, Date modifyDate,String quotaPattern) {
        this.ID = htlQuotaNewId;
        this.ableSaleDate = ableSaleDate;
        this.hotelId = hotelId;
        this.roomtypeId = roomtypeId;
        this.bedId = bedId;
        this.quotaHolder = quotaHolder;
        this.quotaShareType = quotaShareType;
        this.buyQuotaSum = buyQuotaSum;
        this.buyQuotaAbleNum = buyQuotaAbleNum;
        this.buyQuotaUsedNum = buyQuotaUsedNum;
        this.buyQuotaOutofdateNum = buyQuotaOutofdateNum;
        this.commonQuotaSum = commonQuotaSum;
        this.commonQuotaAbleNum = commonQuotaAbleNum;
        this.commonQuotaUsedNum = commonQuotaUsedNum;
        this.commonQuotaOutofdateNum = commonQuotaOutofdateNum;
        this.outsideQuotaSum = outsideQuotaSum;
        this.casualQuotaSum = casualQuotaSum;
        this.casualQuotaAbleNum = casualQuotaAbleNum;
        this.casualQuotaUsedNum = casualQuotaUsedNum;
        this.casualQuotaOutofdateNum = casualQuotaOutofdateNum;
        this.forewarnQuotaNum = forewarnQuotaNum;
        this.forewarnFlag = forewarnFlag;
        this.createDept = createDept;
        this.createId = createId;
        this.createName = createName;
        this.createDate = createDate;
        this.modifyDept = modifyDept;
        this.modifyId = modifyId;
        this.modifyName = modifyName;
        this.modifyDate = modifyDate;
        this.quotaPattern=quotaPattern;
    }

    // Property accessors

    public Date getAbleSaleDate() {
        return this.ableSaleDate;
    }

    public void setAbleSaleDate(Date ableSaleDate) {
        this.ableSaleDate = ableSaleDate;
    }

    public Long getHotelId() {
        return this.hotelId;
    }

    public void setHotelId(Long hotelId) {
        this.hotelId = hotelId;
    }

    public Long getRoomtypeId() {
        return this.roomtypeId;
    }

    public void setRoomtypeId(Long roomtypeId) {
        this.roomtypeId = roomtypeId;
    }

    public Long getBedId() {
        return this.bedId;
    }

    public void setBedId(Long bedId) {
        this.bedId = bedId;
    }

    public String getQuotaHolder() {
        return this.quotaHolder;
    }

    public void setQuotaHolder(String quotaHolder) {
        this.quotaHolder = quotaHolder;
    }

    public Long getQuotaShareType() {
        return this.quotaShareType;
    }

    public void setQuotaShareType(Long quotaShareType) {
        this.quotaShareType = quotaShareType;
    }

    public Long getBuyQuotaSum() {
        return this.buyQuotaSum;
    }

    public void setBuyQuotaSum(Long buyQuotaSum) {
        this.buyQuotaSum = buyQuotaSum;
    }

    public Long getBuyQuotaAbleNum() {
        return this.buyQuotaAbleNum;
    }

    public void setBuyQuotaAbleNum(Long buyQuotaAbleNum) {
        this.buyQuotaAbleNum = buyQuotaAbleNum;
    }

    public Long getBuyQuotaUsedNum() {
        return this.buyQuotaUsedNum;
    }

    public void setBuyQuotaUsedNum(Long buyQuotaUsedNum) {
        this.buyQuotaUsedNum = buyQuotaUsedNum;
    }

    public Long getBuyQuotaOutofdateNum() {
        return this.buyQuotaOutofdateNum;
    }

    public void setBuyQuotaOutofdateNum(Long buyQuotaOutofdateNum) {
        this.buyQuotaOutofdateNum = buyQuotaOutofdateNum;
    }

    public Long getCommonQuotaSum() {
        return this.commonQuotaSum;
    }

    public void setCommonQuotaSum(Long commonQuotaSum) {
        this.commonQuotaSum = commonQuotaSum;
    }

    public Long getCommonQuotaAbleNum() {
        return this.commonQuotaAbleNum;
    }

    public void setCommonQuotaAbleNum(Long commonQuotaAbleNum) {
        this.commonQuotaAbleNum = commonQuotaAbleNum;
    }

    public Long getCommonQuotaUsedNum() {
        return this.commonQuotaUsedNum;
    }

    public void setCommonQuotaUsedNum(Long commonQuotaUsedNum) {
        this.commonQuotaUsedNum = commonQuotaUsedNum;
    }

    public Long getCommonQuotaOutofdateNum() {
        return this.commonQuotaOutofdateNum;
    }

    public void setCommonQuotaOutofdateNum(Long commonQuotaOutofdateNum) {
        this.commonQuotaOutofdateNum = commonQuotaOutofdateNum;
    }

    public Long getOutsideQuotaSum() {
        return this.outsideQuotaSum;
    }

    public void setOutsideQuotaSum(Long outsideQuotaSum) {
        this.outsideQuotaSum = outsideQuotaSum;
    }

    public Long getCasualQuotaSum() {
        return this.casualQuotaSum;
    }

    public void setCasualQuotaSum(Long casualQuotaSum) {
        this.casualQuotaSum = casualQuotaSum;
    }

    public Long getCasualQuotaAbleNum() {
        return this.casualQuotaAbleNum;
    }

    public void setCasualQuotaAbleNum(Long casualQuotaAbleNum) {
        this.casualQuotaAbleNum = casualQuotaAbleNum;
    }

    public Long getCasualQuotaUsedNum() {
        return this.casualQuotaUsedNum;
    }

    public void setCasualQuotaUsedNum(Long casualQuotaUsedNum) {
        this.casualQuotaUsedNum = casualQuotaUsedNum;
    }

    public Long getCasualQuotaOutofdateNum() {
        return this.casualQuotaOutofdateNum;
    }

    public void setCasualQuotaOutofdateNum(Long casualQuotaOutofdateNum) {
        this.casualQuotaOutofdateNum = casualQuotaOutofdateNum;
    }

    public Long getForewarnQuotaNum() {
        return this.forewarnQuotaNum;
    }

    public void setForewarnQuotaNum(Long forewarnQuotaNum) {
        this.forewarnQuotaNum = forewarnQuotaNum;
    }

    public Long getForewarnFlag() {
        return this.forewarnFlag;
    }

    public void setForewarnFlag(Long forewarnFlag) {
        this.forewarnFlag = forewarnFlag;
    }

    public String getCreateDept() {
        return this.createDept;
    }

    public void setCreateDept(String createDept) {
        this.createDept = createDept;
    }

    public String getCreateId() {
        return this.createId;
    }

    public void setCreateId(String createId) {
        this.createId = createId;
    }

    public String getCreateName() {
        return this.createName;
    }

    public void setCreateName(String createName) {
        this.createName = createName;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public String getModifyDept() {
        return this.modifyDept;
    }

    public void setModifyDept(String modifyDept) {
        this.modifyDept = modifyDept;
    }

    public String getModifyId() {
        return this.modifyId;
    }

    public void setModifyId(String modifyId) {
        this.modifyId = modifyId;
    }

    public String getModifyName() {
        return this.modifyName;
    }

    public void setModifyName(String modifyName) {
        this.modifyName = modifyName;
    }

    public Date getModifyDate() {
        return this.modifyDate;
    }

    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    public Long getID() {
        return ID;
    }

    public void setID(Long id) {
        ID = id;
    }

	public Long getForewarnYesOrNo() {
		return forewarnYesOrNo;
	}

	public void setForewarnYesOrNo(Long forewarnYesOrNo) {
		this.forewarnYesOrNo = forewarnYesOrNo;
	}

	public Integer getCanUserQuotaNum() {
		return canUserQuotaNum;
	}

	public void setCanUserQuotaNum(Integer canUserQuotaNum) {
		this.canUserQuotaNum = canUserQuotaNum;
	}

	public String getQuotaPattern() {
		return quotaPattern;
	}

	public void setQuotaPattern(String quotaPattern) {
		this.quotaPattern = quotaPattern;
	}

}