package com.mangocity.hotel.base.persistence;

import java.util.Date;

import com.mangocity.hotel.base.web.InitServlet;


/**
 * HtlRoomcontrolHotelSchedule generated by MyEclipse Persistence Tools
 * 房控酒店列表
 */

public class HtlRoomcontrolHotelSchedule implements java.io.Serializable {

	// Fields
	/**
	 * 主键ID
	 */
	private Long scheduleid;
	/**
	 * 日期
	 */
	private Date scheduledate;
	/**
	 * 酒店ID
	 */
	private Long hotelid;
	/**
	 * 当前分配人工号
	 */
	private String nowassignedid;
	/**
	 * 当前分配人名
	 */
	private String nowassignedname;
	/**
	 * 获取方式：1，自动2，手工
	 */
	private Integer acquireway;
	/**
	 * 城市
	 */
	private String hotelcity;
	/**
	 * 省份
	 */
	private String hotelstate;
	/**
	 * 城区
	 */
	private String hotelzone;
	/**
	 * 商业区
	 */
	private String hotelbizzone;
	/**
	 * 当天日立起前推6个月累加间夜量
	 */
	private Integer nightcounthalfyearhotel;
	/**
	 * 是否配额预警酒店
	 */
	private Integer quotawarninghotel;
	/**
	 * 满房拒单率
	 */
	private Double fullroomrejectratehotel;
	/**
	 * E-price 酒店是否需要审核 1:需要 0:不需要
	 */
	private Integer epriceaudithotel;
	/**
	 * 巡房时间点
	 */
	private Integer checkPoint = new Integer(22);
	/**
	 * 最后修改时间
	 */
	private Date modifytime;
	/**
	 * 修改过的员工ID，以,分隔
	 */
	private String modifybyid;
	/**
	 * 修改过的员工名，以,分隔
	 */
	private String modifybyname;
	/**
	 * 酒店中文名
	 */
	private String hotelname;
	/**
	 * 酒店星级
	 */
	private String hotelstar;
	/**
	 * 会展酒店
	 */
	private Integer exhibitionhotel;
	/**
	 * 推荐类型（特推，金牌，银牌）
	 */
	private Integer commendtypehotel;
	/**
	 * 获取状态：0,未获取 1,已获取
	 */
	private Integer acquirestate;
	/**
	 * 状态，0：未处理，1：最少处理过一次
	 */
	private Integer state;
	/**
	 * 产品经理人
	 */
	private String productmanager;
	/**
	 * CC设满房，关房
	 */
	private Integer ccsetroomfullorclose;
	/**
	 * 此酒店此时共询房次数
	 */
	private Integer setup;
	/**
	 * 当前操作日志的ID，以便于更新操作此次日志
	 */
	private Long operationlogid;
	/**
	 * 酒店英文名
	 */
	private String englishname;
	
	/**
	 * 房态负责人
	 */
	private String roomStateManger;
	/**
	 * 是否青芒果标志
	 */
	private String isGreenMangoHotel;
	
	/**
	 * 酒店合作类型(直联合作方) 系统内酒店是0
	 */
	private Integer cooperateChannel = new Integer(0);
	/**
	 * E-price(满房 系统内配额大于0 需要审核) 2:包含今天,1:包含今天以后,0:不需要审核或其他
	 */
	private Integer epriceFullRoomAudit = new Integer(0);
	/**
	 * 售卖状态 0:停止售卖,1:正常售卖,2:从停止售卖转成正常售卖
	 */
	private Integer hotelSellState = new Integer(1);
	/**
	 * 是否有FreeSale房型的酒店，1：是   ,  0 ：否
	 */
	private Integer freeSaleHotel ;

	/**
	 * 是否eprice酒店
	 */
	private Integer epriceHotel = new Integer(0);
	
	/**
	 * 入住日期是今天的间夜量
	 */
	private Integer nightCountThree;
	
	/**
	 * 入住日期是明天的间夜量
	 */
	private Integer nightCountFour;
	
	/**
	 * 入住日期是后天的间夜量
	 */
	private Integer nightCountFive;
	
	// Constructors

	/** default constructor */
	public HtlRoomcontrolHotelSchedule() {
	}

	// Property accessors

	public Long getScheduleid() {
		return this.scheduleid;
	}

	public void setScheduleid(Long scheduleid) {
		this.scheduleid = scheduleid;
	}

	public Date getScheduledate() {
		return this.scheduledate;
	}

	public void setScheduledate(Date scheduledate) {
		this.scheduledate = scheduledate;
	}

	public Long getHotelid() {
		return this.hotelid;
	}

	public void setHotelid(Long hotelid) {
		this.hotelid = hotelid;
	}

	public String getNowassignedid() {
		return this.nowassignedid;
	}

	public void setNowassignedid(String nowassignedid) {
		this.nowassignedid = nowassignedid;
	}

	public String getNowassignedname() {
		return this.nowassignedname;
	}

	public void setNowassignedname(String nowassignedname) {
		this.nowassignedname = nowassignedname;
	}

	public Integer getAcquireway() {
		return this.acquireway;
	}

	public void setAcquireway(Integer acquireway) {
		if (null == acquireway){
			this.acquireway = 0;
		}else{
			this.acquireway = acquireway;
		}
	}

	public String getHotelcity() {
		return this.hotelcity;
	}

	public String getHotelcityStr() {
		return InitServlet.cityObj.get(this.hotelcity);
	}
	
	public void setHotelcity(String hotelcity) {
		this.hotelcity = hotelcity;
	}

	public String getHotelstateStr() {
		return InitServlet.ProvinceObj.get(this.hotelstate);
	}
	
	public String getHotelstate() {
		return this.hotelstate;
	}

	public void setHotelstate(String hotelstate) {
		this.hotelstate = hotelstate;
	}

	public String getHotelzone() {
		return this.hotelzone;
	}
	
	public String getHotelzoneStr() {
		return InitServlet.citySozeObj.get(this.hotelzone);
	}
	
	public void setHotelzone(String hotelzone) {
		this.hotelzone = hotelzone;
	}

	public String getHotelbizzone() {
		return this.hotelbizzone;
	}

	public void setHotelbizzone(String hotelbizzone) {
		this.hotelbizzone = hotelbizzone;
	}

	public Integer getNightcounthalfyearhotel() {
		return this.nightcounthalfyearhotel;
	}

	public void setNightcounthalfyearhotel(Integer nightcounthalfyearhotel) {
		this.nightcounthalfyearhotel = nightcounthalfyearhotel;
	}

	public Integer getQuotawarninghotel() {
		return this.quotawarninghotel;
	}

	public void setQuotawarninghotel(Integer quotawarninghotel) {
		this.quotawarninghotel = quotawarninghotel;
	}

	public Double getFullroomrejectratehotel() {
		return this.fullroomrejectratehotel;
	}

	public void setFullroomrejectratehotel(Double fullroomrejectratehotel) {
		this.fullroomrejectratehotel = fullroomrejectratehotel;
	}

	public Integer getEpriceaudithotel() {
		return this.epriceaudithotel;
	}

	public void setEpriceaudithotel(Integer epriceaudithotel) {
		this.epriceaudithotel = epriceaudithotel;
	}

	public Date getModifytime() {
		return this.modifytime;
	}

	public void setModifytime(Date modifytime) {
		this.modifytime = modifytime;
	}

	public String getModifybyid() {
		return this.modifybyid;
	}

	public void setModifybyid(String modifybyid) {
		this.modifybyid = modifybyid;
	}

	public String getModifybyname() {
		return this.modifybyname;
	}

	public void setModifybyname(String modifybyname) {
		this.modifybyname = modifybyname;
	}


	public String getHotelname() {
		return this.hotelname;
	}

	public void setHotelname(String hotelname) {
		this.hotelname = hotelname;
	}

	public String getHotelstar() {
		return this.hotelstar;
	}

	public void setHotelstar(String hotelstar) {
		this.hotelstar = hotelstar;
	}

	public Integer getExhibitionhotel() {
		return this.exhibitionhotel;
	}

	public void setExhibitionhotel(Integer exhibitionhotel) {
		this.exhibitionhotel = exhibitionhotel;
	}

	public Integer getCommendtypehotel() {
		return this.commendtypehotel;
	}

	public void setCommendtypehotel(Integer commendtypehotel) {
		this.commendtypehotel = commendtypehotel;
	}

	public Integer getAcquirestate() {
		return this.acquirestate;
	}

	public void setAcquirestate(Integer acquirestate) {
		this.acquirestate = acquirestate;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public String getProductmanager() {
		return this.productmanager;
	}

	public void setProductmanager(String productmanager) {
		this.productmanager = productmanager;
	}

	public Integer getCcsetroomfullorclose() {
		return this.ccsetroomfullorclose;
	}

	public void setCcsetroomfullorclose(Integer ccsetroomfullorclose) {
		this.ccsetroomfullorclose = ccsetroomfullorclose;
	}

	public Integer getSetup() {
		return this.setup;
	}

	public void setSetup(Integer setup) {
		this.setup = setup;
	}

	public Long getOperationlogid() {
		return this.operationlogid;
	}

	public void setOperationlogid(Long operationlogid) {
		this.operationlogid = operationlogid;
	}

	public String getEnglishname() {
		return this.englishname;
	}

	public void setEnglishname(String englishname) {
		this.englishname = englishname;
	}

	public Integer getCheckPoint() {
		return checkPoint;
	}

	public void setCheckPoint(Integer checkPoint) {
		this.checkPoint = checkPoint;
	}

	public String getIsGreenMangoHotel() {
		return isGreenMangoHotel;
	}

	public void setIsGreenMangoHotel(String isGreenMangoHotel) {
		this.isGreenMangoHotel = isGreenMangoHotel;
	}

	public String getRoomStateManger() {
		return roomStateManger;
	}

	public void setRoomStateManger(String roomStateManger) {
		this.roomStateManger = roomStateManger;
	}
	
	public Integer getCooperateChannel() {
		return cooperateChannel;
	}

	public void setCooperateChannel(Integer cooperateChannel) {
		this.cooperateChannel = cooperateChannel;
	}

	public Integer getEpriceFullRoomAudit() {
		return epriceFullRoomAudit;
	}

	public void setEpriceFullRoomAudit(Integer epriceFullRoomAudit) {
		this.epriceFullRoomAudit = epriceFullRoomAudit;
	}

	public Integer getHotelSellState() {
		return hotelSellState;
	}

	public void setHotelSellState(Integer hotelSellState) {
		this.hotelSellState = hotelSellState;
	}

    public Integer getEpriceHotel() {
        return epriceHotel;
    }

    public void setEpriceHotel(Integer epriceHotel) {
        this.epriceHotel = epriceHotel;
    }

	public Integer getFreeSaleHotel() {
		return freeSaleHotel;
	}

	public void setFreeSaleHotel(Integer freeSaleHotel) {
		this.freeSaleHotel = freeSaleHotel;
	}
	public Integer getNightCountThree() {
		return nightCountThree;
	}

	public void setNightCountThree(Integer nightCountThree) {
		this.nightCountThree = nightCountThree;
	}

	public Integer getNightCountFour() {
		return nightCountFour;
	}

	public void setNightCountFour(Integer nightCountFour) {
		this.nightCountFour = nightCountFour;
	}

	public Integer getNightCountFive() {
		return nightCountFive;
	}

	public void setNightCountFive(Integer nightCountFive) {
		this.nightCountFive = nightCountFive;
	}

}