package com.mangocity.hotel.base.persistence;

import java.util.*;

import com.mangocity.util.Entity;

/**
 * HtlReservationBatch generated by MyEclipse Persistence Tools
 */

public class HtlReservationBatch extends CEntity implements Entity {

    // Fields

    private Long id;

    private HtlPreconcertItemBatch htlPreconcertItemBatch;

    private Long aheadDay;

    private String aheadTime;

    private Date mustAheadDate;

    private String mustAheadTime;

    private String continueNights;

    private String maxRestrictNights;

    private String minRestrictNights;
    
    /**
     * add by shengwei.zuo 预定条款的时限 新增时间段的的预订规则 2009-09-03 begin
     */
    //必须的起始日期  
    private Date mustFromDate;
    
    //必须的截止日期
    private Date mustToDate;
    
    //必须的起始时间  
    private String mustFromTime;
    
    //必须的截止时间
    private String mustToTime;
    
    /**
     * add by shengwei.zuo 预定条款的时限 新增时间段的的预订规则 2009-09-03 end
     */

    private List htlReservContBatch;

    /*
     * ����lס���ڵĹ�ϵ,���� or ����
     */
    private String continueDatesRelation;

    // Constructors

    public String getContinueDatesRelation() {
        return continueDatesRelation;
    }

    public void setContinueDatesRelation(String continueDatesRelation) {
        this.continueDatesRelation = continueDatesRelation;
    }

    public List getHtlReservContBatch() {
        return htlReservContBatch;
    }

    public void setHtlReservContBatch(List htlReservContBatch) {
        this.htlReservContBatch = htlReservContBatch;
    }

    /** default constructor */
    public HtlReservationBatch() {
    }

    // Property accessors

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAheadDay() {
        return this.aheadDay;
    }

    public void setAheadDay(Long aheadDay) {
        this.aheadDay = aheadDay;
    }

    public String getAheadTime() {
        return this.aheadTime;
    }

    public void setAheadTime(String aheadTime) {
        this.aheadTime = aheadTime;
    }

    public Date getMustAheadDate() {
        return this.mustAheadDate;
    }

    public void setMustAheadDate(Date mustAheadDate) {
        this.mustAheadDate = mustAheadDate;
    }

    public String getMustAheadTime() {
        return this.mustAheadTime;
    }

    public void setMustAheadTime(String mustAheadTime) {
        this.mustAheadTime = mustAheadTime;
    }

    public String getContinueNights() {
        return continueNights;
    }

    public void setContinueNights(String continueNights) {
        this.continueNights = continueNights;
    }

    public HtlPreconcertItemBatch getHtlPreconcertItemBatch() {
        return htlPreconcertItemBatch;
    }

    public void setHtlPreconcertItemBatch(HtlPreconcertItemBatch htlPreconcertItemBatch) {
        this.htlPreconcertItemBatch = htlPreconcertItemBatch;
    }

    public Long getID() {
        // TODO Auto-generated method stub
        return id;
    }

    public String getMaxRestrictNights() {
        return maxRestrictNights;
    }

    public void setMaxRestrictNights(String maxRestrictNights) {
        this.maxRestrictNights = maxRestrictNights;
    }

    public String getMinRestrictNights() {
        return minRestrictNights;
    }

    public void setMinRestrictNights(String minRestrictNights) {
        this.minRestrictNights = minRestrictNights;
    }

	public Date getMustFromDate() {
		return mustFromDate;
	}

	public void setMustFromDate(Date mustFromDate) {
		this.mustFromDate = mustFromDate;
	}

	public Date getMustToDate() {
		return mustToDate;
	}

	public void setMustToDate(Date mustToDate) {
		this.mustToDate = mustToDate;
	}

	public String getMustFromTime() {
		return mustFromTime;
	}

	public void setMustFromTime(String mustFromTime) {
		this.mustFromTime = mustFromTime;
	}

	public String getMustToTime() {
		return mustToTime;
	}

	public void setMustToTime(String mustToTime) {
		this.mustToTime = mustToTime;
	}

}