package com.mangocity.hotel.base.persistence;

import java.util.Date;

import com.mangocity.util.Entity;

/**
 * HtlRewardinfo generated by MyEclipse - Hibernate Tools 奖励政策条款
 */

public class HtlRewardInfo extends CEntity implements Entity {

    // Fields
    // 奖励政策id+
    private Long ID;

    // 合同id
    private long contractID;

    /**
     * 房型id
     */
    private String roomTypeId;

    // 分期类型
    private String dateType;

    // 销售类型
    private String saleType;

    // 完成类型
    private String doneType;

    // 销售房间数量
    private int roomAmount;

    // 销售金额
    private double saleAmount;

    // 开始间夜
    private int beginNight;

    // 结束间夜
    private int endNight;

    // 赚送间夜
    private int presentNight;

    // 赠送房型
    private long presentRoomType;

    // 奖励销售额百分比
    private double bonusScale;

    // 奖励类型
    private String forwardType;

    // 使用期限
    private String lastUseDate;

    // 起始有效时间
    private Date beginUseDate;

    // 终止有效时间
    private Date endUseDate;

    // 每间夜奖金
    private double everydayBonus;

    // 限制条款

    private String confineItem;

    // 免费房使用的开始时间
    private Date beginFreeUseDate;

    // 免费房使用的结束时间
    private Date endFreeUseDate;

    // Constructors

    // Constructors

    /** default constructor */
    public HtlRewardInfo() {
    }

    public int getBeginNight() {
        return beginNight;
    }

    public void setBeginNight(int beginNight) {
        this.beginNight = beginNight;
    }

    public double getBonusScale() {
        return bonusScale;
    }

    public void setBonusScale(double bonusScale) {
        this.bonusScale = bonusScale;
    }

    public long getContractID() {
        return contractID;
    }

    public void setContractID(long contractId) {
        this.contractID = contractId;
    }

    public String getDateType() {
        return dateType;
    }

    public void setDateType(String dateType) {
        this.dateType = dateType;
    }

    public String getDoneType() {
        return doneType;
    }

    public void setDoneType(String doneType) {
        this.doneType = doneType;
    }

    public int getEndNight() {
        return endNight;
    }

    public void setEndNight(int endNight) {
        this.endNight = endNight;
    }

    public String getForwardType() {
        return forwardType;
    }

    public void setForwardType(String forwardType) {
        this.forwardType = forwardType;
    }

    public Long getID() {
        return ID;
    }

    public void setID(Long id) {
        ID = id;
    }

    public String getLastUseDate() {
        return lastUseDate;
    }

    public void setLastUseDate(String lastUseDate) {
        this.lastUseDate = lastUseDate;
    }

    public int getPresentNight() {
        return presentNight;
    }

    public void setPresentNight(int presentNight) {
        this.presentNight = presentNight;
    }

    public long getPresentRoomType() {
        return presentRoomType;
    }

    public void setPresentRoomType(long presentRoomType) {
        this.presentRoomType = presentRoomType;
    }

    public int getRoomAmount() {
        return roomAmount;
    }

    public void setRoomAmount(int roomAmount) {
        this.roomAmount = roomAmount;
    }

    public double getSaleAmount() {
        return saleAmount;
    }

    public void setSaleAmount(double saleAmount) {
        this.saleAmount = saleAmount;
    }

    public String getSaleType() {
        return saleType;
    }

    public void setSaleType(String saleType) {
        this.saleType = saleType;
    }

    public Date getBeginUseDate() {
        return beginUseDate;
    }

    public void setBeginUseDate(Date beginUseDate) {
        this.beginUseDate = beginUseDate;
    }

    public String getConfineItem() {
        return confineItem;
    }

    public void setConfineItem(String confineItem) {
        this.confineItem = confineItem;
    }

    public Date getEndUseDate() {
        return endUseDate;
    }

    public void setEndUseDate(Date endUseDate) {
        this.endUseDate = endUseDate;
    }

    public double getEverydayBonus() {
        return everydayBonus;
    }

    public void setEverydayBonus(double everydayBonus) {
        this.everydayBonus = everydayBonus;
    }

    public String getRoomTypeId() {
        return roomTypeId;
    }

    public void setRoomTypeId(String roomTypeId) {
        this.roomTypeId = roomTypeId;
    }

    public Date getBeginFreeUseDate() {
        return beginFreeUseDate;
    }

    public void setBeginFreeUseDate(Date beginFreeUseDate) {
        this.beginFreeUseDate = beginFreeUseDate;
    }

    public Date getEndFreeUseDate() {
        return endFreeUseDate;
    }

    public void setEndFreeUseDate(Date endFreeUseDate) {
        this.endFreeUseDate = endFreeUseDate;
    }

}
