package com.mangocity.hotel.base.persistence;

import java.util.Date;

import com.mangocity.util.Entity;

/**
 * HtlReservContBatch generated by MyEclipse Persistence Tools
 */

public class HtlReservContBatch extends CEntity implements Entity {

    // Fields

    private Long id;

    private HtlReservationBatch htlReservationBatch;

    private Date continueDate;

    private Date continueEndDate;

    private String weeks;

    public Date getContinueEndDate() {
        return continueEndDate;
    }

    public void setContinueEndDate(Date continueEndDate) {
        this.continueEndDate = continueEndDate;
    }

    public String getWeeks() {
        return weeks;
    }

    public void setWeeks(String weeks) {
        this.weeks = weeks;
    }

    // Constructors

    /** default constructor */
    public HtlReservContBatch() {
    }

    // Property accessors

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public HtlReservationBatch getHtlReservationBatch() {
        return htlReservationBatch;
    }

    public void setHtlReservationBatch(HtlReservationBatch htlReservationBatch) {
        this.htlReservationBatch = htlReservationBatch;
    }

    public Date getContinueDate() {
        return this.continueDate;
    }

    public void setContinueDate(Date continueDate) {
        this.continueDate = continueDate;
    }

    public Long getID() {
        // TODO Auto-generated method stub
        return id;
    }

    @Override
    /*
     * * ��дequals��hashCode����,�Ƚ�}���סʱ���Ƿ���� Add by chenjuesu
     */
    public boolean equals(Object obj) {
        // TODO Auto-generated method stub
        return obj instanceof HtlReservContTemplate
            && this.continueDate.getTime() == ((HtlReservContTemplate) obj).getContinueDate()
                .getTime();
    }

    public int hashCode() {
        long ht = this.continueDate.getTime();
        return Long.valueOf(ht).intValue() ^ Long.valueOf(ht >> 32).intValue();
    }
}