package hk.com.cts.ctcp.hotel.webservice.commonservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;// parasoft-suppress UC.UIMPORT "必须引入"
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version:
 * 2.0
 * 
 */
@WebService(name = "CommonService", targetNamespace = "http://common.hotel.ws.ctcp.cts.com")
public interface CommonService {

    /**
     * 
     * @param sAgentCode
     * @return returns hk.com.cts.ctcp.hotel.webservice.commonService.AppRegData
     */
    @WebMethod
    @WebResult(name = "comAppRegReturn", targetNamespace = "http://common.hotel.ws.ctcp.cts.com")
    @RequestWrapper(localName = "comAppReg", 
            targetNamespace = "http://common.hotel.ws.ctcp.cts.com", 
            className = "hk.com.cts.ctcp.hotel.webservice.commonservice.ComAppReg")
    @ResponseWrapper(localName = "comAppRegResponse", 
            targetNamespace = "http://common.hotel.ws.ctcp.cts.com", 
            className = "hk.com.cts.ctcp.hotel.webservice.commonservice.ComAppRegResponse")
    public AppRegData comAppReg(
        @WebParam(name = "sAgentCode", 
                targetNamespace = "http://common.hotel.ws.ctcp.cts.com") 
                String sAgentCode);

}
