package hk.com.cts.ctcp.hotel.webservice.saleservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;// parasoft-suppress UC.UIMPORT "必须引入"
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.4 Tue Apr 07 19:30:54 CST 2009 Generated source
 * version: 2.1.4
 * 
 */

@WebService(targetNamespace = "http://sale.hotel.ws.ctcp.cts.com", name = "SaleService")
@XmlSeeAlso( { ObjectFactory.class })
public interface SaleService {

    @ResponseWrapper(localName = "saleAddCustInfoResponse", 
            targetNamespace = "http://sale.hotel.ws.ctcp.cts.com", 
            className = "com.cts.ctcp.ws.hotel.sale.SaleAddCustInfoResponse")
    @RequestWrapper(localName = "saleAddCustInfo", 
            targetNamespace = "http://sale.hotel.ws.ctcp.cts.com", 
            className = "com.cts.ctcp.ws.hotel.sale.SaleAddCustInfo")
    @WebResult(name = "saleAddCustInfoReturn", 
            targetNamespace = "http://sale.hotel.ws.ctcp.cts.com")
    @WebMethod
    public BasicData saleAddCustInfo(
        @WebParam(name = "sApiKey", 
                targetNamespace = "http://sale.hotel.ws.ctcp.cts.com") 
                java.lang.String sApiKey,
        @WebParam(name = "sTxnNo", 
                targetNamespace = "http://sale.hotel.ws.ctcp.cts.com") 
                java.lang.String sTxnNo,
        @WebParam(name = "aInfo", 
                targetNamespace = "http://sale.hotel.ws.ctcp.cts.com") 
                java.util.List<CustInfo> aInfo,
        @WebParam(name = "sRmk", 
                targetNamespace = "http://sale.hotel.ws.ctcp.cts.com") 
                java.lang.String sRmk);

    @ResponseWrapper(localName = "saleAddItemResponse", 
            targetNamespace = "http://sale.hotel.ws.ctcp.cts.com", 
            className = "com.cts.ctcp.ws.hotel.sale.SaleAddItemResponse")
    @RequestWrapper(localName = "saleAddItem", 
            targetNamespace = "http://sale.hotel.ws.ctcp.cts.com", 
            className = "com.cts.ctcp.ws.hotel.sale.SaleAddItem")
    @WebResult(name = "saleAddItemReturn", 
            targetNamespace = "http://sale.hotel.ws.ctcp.cts.com")
    @WebMethod
    public AddItemData saleAddItem(
        @WebParam(name = "sApiKey", 
                targetNamespace = "http://sale.hotel.ws.ctcp.cts.com") 
                java.lang.String sApiKey,
        @WebParam(name = "sTxnNo", 
                targetNamespace = "http://sale.hotel.ws.ctcp.cts.com") 
                java.lang.String sTxnNo,
        @WebParam(name = "sHotelCode", 
                targetNamespace = "http://sale.hotel.ws.ctcp.cts.com") 
                java.lang.String sHotelCode,
        @WebParam(name = "sDate", 
                targetNamespace = "http://sale.hotel.ws.ctcp.cts.com") 
                java.lang.String sDate,
        @WebParam(name = "sClassCode", 
                targetNamespace = "http://sale.hotel.ws.ctcp.cts.com") 
                java.lang.String sClassCode,
        @WebParam(name = "sNationCode", 
                targetNamespace = "http://sale.hotel.ws.ctcp.cts.com") 
                java.lang.String sNationCode,
        @WebParam(name = "nQty", 
                targetNamespace = "http://sale.hotel.ws.ctcp.cts.com") 
                int nQty);

    @ResponseWrapper(localName = "saleRollbackResponse", 
            targetNamespace = "http://sale.hotel.ws.ctcp.cts.com", 
            className = "com.cts.ctcp.ws.hotel.sale.SaleRollbackResponse")
    @RequestWrapper(localName = "saleRollback", 
            targetNamespace = "http://sale.hotel.ws.ctcp.cts.com", 
            className = "com.cts.ctcp.ws.hotel.sale.SaleRollback")
    @WebResult(name = "saleRollbackReturn", 
            targetNamespace = "http://sale.hotel.ws.ctcp.cts.com")
    @WebMethod
    public BasicData saleRollback(
        @WebParam(name = "sTxnNo", 
                targetNamespace = "http://sale.hotel.ws.ctcp.cts.com") 
                java.lang.String sTxnNo);

    @ResponseWrapper(localName = "saleBeginResponse", 
            targetNamespace = "http://sale.hotel.ws.ctcp.cts.com", 
            className = "com.cts.ctcp.ws.hotel.sale.SaleBeginResponse")
    @RequestWrapper(localName = "saleBegin", 
            targetNamespace = "http://sale.hotel.ws.ctcp.cts.com", 
            className = "com.cts.ctcp.ws.hotel.sale.SaleBegin")
    @WebResult(name = "saleBeginReturn", 
            targetNamespace = "http://sale.hotel.ws.ctcp.cts.com")
    @WebMethod
    public BeginData saleBegin(
        @WebParam(name = "sApiKey", 
                targetNamespace = "http://sale.hotel.ws.ctcp.cts.com") 
                java.lang.String sApiKey);

    @ResponseWrapper(localName = "saleCommitResponse", 
            targetNamespace = "http://sale.hotel.ws.ctcp.cts.com", 
            className = "com.cts.ctcp.ws.hotel.sale.SaleCommitResponse")
    @RequestWrapper(localName = "saleCommit", 
            targetNamespace = "http://sale.hotel.ws.ctcp.cts.com", 
            className = "com.cts.ctcp.ws.hotel.sale.SaleCommit")
    @WebResult(name = "saleCommitReturn", 
            targetNamespace = "http://sale.hotel.ws.ctcp.cts.com")
    @WebMethod
    public BasicData saleCommit(
        @WebParam(name = "sApiKey", 
                targetNamespace = "http://sale.hotel.ws.ctcp.cts.com") 
                java.lang.String sApiKey,
        @WebParam(name = "sTxnNo", 
                targetNamespace = "http://sale.hotel.ws.ctcp.cts.com") 
                java.lang.String sTxnNo,
        @WebParam(name = "nTotQty", 
                targetNamespace = "http://sale.hotel.ws.ctcp.cts.com") 
                int nTotQty);

    @ResponseWrapper(localName = "saleCalAmtResponse", 
            targetNamespace = "http://sale.hotel.ws.ctcp.cts.com", 
            className = "com.cts.ctcp.ws.hotel.sale.SaleCalAmtResponse")
    @RequestWrapper(localName = "saleCalAmt", 
            targetNamespace = "http://sale.hotel.ws.ctcp.cts.com", 
            className = "com.cts.ctcp.ws.hotel.sale.SaleCalAmt")
    @WebResult(name = "saleCalAmtReturn", 
            targetNamespace = "http://sale.hotel.ws.ctcp.cts.com")
    @WebMethod
    public CalAmtData saleCalAmt(
        @WebParam(name = "sApiKey", 
                targetNamespace = "http://sale.hotel.ws.ctcp.cts.com") 
                java.lang.String sApiKey,
        @WebParam(name = "sTxnNo",
                targetNamespace = "http://sale.hotel.ws.ctcp.cts.com")
                java.lang.String sTxnNo);
}
