package com.mangocity.hotel.order.persistence;

import java.util.Date;

import com.mangocity.util.Entity;

/**
 * AbstractHtlRoomstateCcBed generated by MyEclipse Persistence Tools
 */

public  class HtlRoomstateCcBed implements Entity {

    // Fields
    
    
    private Long ID;

    private Date roomdate;

    private Long roomtypeid;

    private String roomtypenm;

    private String bedidstr;

    private Long quotanum;

    private String roomstate;
    
    private HtlRoomstateCc htlRoomstateCc;


    public String getBedidstr() {
        return bedidstr;
    }

    public void setBedidstr(String bedidstr) {
        this.bedidstr = bedidstr;
    }

    public Long getID() {
        return ID;
    }

    public void setID(Long id) {
        ID = id;
    }

    public Long getQuotanum() {
        return quotanum;
    }

    public void setQuotanum(Long quotanum) {
        this.quotanum = quotanum;
    }

    public Date getRoomdate() {
        return roomdate;
    }

    public void setRoomdate(Date roomdate) {
        this.roomdate = roomdate;
    }

    public String getRoomstate() {
        return roomstate;
    }

    public void setRoomstate(String roomstate) {
        this.roomstate = roomstate;
    }

    public Long getRoomtypeid() {
        return roomtypeid;
    }

    public void setRoomtypeid(Long roomtypeid) {
        this.roomtypeid = roomtypeid;
    }

    public String getRoomtypenm() {
        return roomtypenm;
    }

    public void setRoomtypenm(String roomtypenm) {
        this.roomtypenm = roomtypenm;
    }

    public HtlRoomstateCc getHtlRoomstateCc() {
        return htlRoomstateCc;
    }

    public void setHtlRoomstateCc(HtlRoomstateCc htlRoomstateCc) {
        this.htlRoomstateCc = htlRoomstateCc;
    }





    // Property accessors


}