package com.mangocity.hotel.order.persistence;

import java.util.Date;
import java.util.List;
import com.mangocity.util.Entity;

/**
 * AbstractHtlRoomstateCc generated by MyEclipse Persistence Tools
 */

public  class HtlRoomstateCc implements Entity {

    // Fields
    /**
     * 序号
     */
    private Long ID;

    private Long roomstateccid;
    
    /**
	 * 酒店ID
	 */
    private Long hotelid;

    /**
	 * 开始日期
	 */
    private Date begindate;

    /**
	 * 结束日期
	 */
    private Date enddate;

    /**
	 * 通知方式
	 */
    private String inform;

    /**
	 * 操作人部门 B为本部 C为CC
	 */
    private String operatedept;

    /**
	 * 操作人名称
	 */
    private String processby;

    /**
	 * 操作人ID
	 */
    private String processbyid;

    /**
	 * 备注
	 */
    private String remark;
    /**
	 * 操作时间
	 */
    private Date processdatetime;

    /**
	 * 操作日期
	 */
    private Date processdate;

    /**
	 * Review部门
	 */
    private String reviewdept;

    /**
	 * ReviewNM
	 */
    private String reviewname;

    /**
	 * ReviewID
	 */
    private String reviewid;

    /**
	 * Review备注
	 */
    private String reviewremark;

    /**
	 * Review状态 默认为0，review后为1
	 */
    private String reviewstate;


    private List htlRoomstateCcBed;



    
    // Property accessors

    public Long getHotelid() {
        return this.hotelid;
    }

    public void setHotelid(Long hotelid) {
        this.hotelid = hotelid;
    }

    public Date getBegindate() {
        return this.begindate;
    }

    public void setBegindate(Date begindate) {
        this.begindate = begindate;
    }

    public Date getEnddate() {
        return this.enddate;
    }

    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    public String getInform() {
        return this.inform;
    }

    public void setInform(String inform) {
        this.inform = inform;
    }

    public String getOperatedept() {
        return this.operatedept;
    }

    public void setOperatedept(String operatedept) {
        this.operatedept = operatedept;
    }

    public String getProcessby() {
        return this.processby;
    }

    public void setProcessby(String processby) {
        this.processby = processby;
    }

    public Date getProcessdatetime() {
        return this.processdatetime;
    }

    public void setProcessdatetime(Date processdatetime) {
        this.processdatetime = processdatetime;
    }

    public Date getProcessdate() {
        return this.processdate;
    }

    public void setProcessdate(Date processdate) {
        this.processdate = processdate;
    }

    public String getReviewdept() {
        return this.reviewdept;
    }

    public void setReviewdept(String reviewdept) {
        this.reviewdept = reviewdept;
    }

    public String getReviewname() {
        return this.reviewname;
    }

    public void setReviewname(String reviewname) {
        this.reviewname = reviewname;
    }



    public String getReviewremark() {
        return this.reviewremark;
    }

    public void setReviewremark(String reviewremark) {
        this.reviewremark = reviewremark;
    }

    public String getReviewstate() {
        return this.reviewstate;
    }

    public void setReviewstate(String reviewstate) {
        this.reviewstate = reviewstate;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Long getID() {
        return ID;
    }

    public void setID(Long id) {
        ID = id;
    }

    public List getHtlRoomstateCcBed() {
        return htlRoomstateCcBed;
    }

    public void setHtlRoomstateCcBed(List htlRoomstateCcBed) {
        this.htlRoomstateCcBed = htlRoomstateCcBed;
    }

    public Long getRoomstateccid() {
        return roomstateccid;
    }

    public void setRoomstateccid(Long roomstateccid) {
        this.roomstateccid = roomstateccid;
    }

    public String getProcessbyid() {
        return processbyid;
    }

    public void setProcessbyid(String processbyid) {
        this.processbyid = processbyid;
    }

    public String getReviewid() {
        return reviewid;
    }

    public void setReviewid(String reviewid) {
        this.reviewid = reviewid;
    }




}