package com.mangocity.hotel.order.persistence;
// default package

import java.util.Date;

/**
 * Myworkingrate generated by MyEclipse Persistence Tools
 */

public class Myworkingrate implements java.io.Serializable {

	// Fields

	private Long id;

	private Date operatordate;

	private String operatorid;

	private String operatorname;
	/**
	 * 组别
	 */
	private Integer grouptype;
	/**
	 * 处理订单量
	 */
	private Integer orderprocessmount;
	/**
	 * 总处理时长
	 */
	private Integer orderprocesstimes;
	/**
	 * 工作效率
	 */
	private Float workingrate;
	/**
	 * 释放订单量
	 */
	private Integer relaxordermount;
	/**
	 * 释放时长
	 */
	private Integer relaxtimes;

	// Constructors

	/** default constructor */
	public Myworkingrate() {
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Date getOperatordate() {
		return this.operatordate;
	}

	public void setOperatordate(Date operatordate) {
		this.operatordate = operatordate;
	}

	public String getOperatorid() {
		return this.operatorid;
	}

	public void setOperatorid(String operatorid) {
		this.operatorid = operatorid;
	}

	public String getOperatorname() {
		return this.operatorname;
	}

	public void setOperatorname(String operatorname) {
		this.operatorname = operatorname;
	}

	public Integer getGrouptype() {
		return this.grouptype;
	}

	public void setGrouptype(Integer grouptype) {
		this.grouptype = grouptype;
	}

	public Integer getOrderprocessmount() {
		return this.orderprocessmount;
	}

	public void setOrderprocessmount(Integer orderprocessmount) {
		this.orderprocessmount = orderprocessmount;
	}

	public Integer getOrderprocesstimes() {
		return this.orderprocesstimes;
	}

	public void setOrderprocesstimes(Integer orderprocesstimes) {
		this.orderprocesstimes = orderprocesstimes;
	}

	public Float getWorkingrate() {
		return this.workingrate;
	}

	public void setWorkingrate(Float workingrate) {
		this.workingrate = workingrate;
	}

	public Integer getRelaxordermount() {
		return this.relaxordermount;
	}

	public void setRelaxordermount(Integer relaxordermount) {
		this.relaxordermount = relaxordermount;
	}

	public Integer getRelaxtimes() {
		return this.relaxtimes;
	}

	public void setRelaxtimes(Integer relaxtimes) {
		this.relaxtimes = relaxtimes;
	}
}